// ralph-gui/ui/src/components/sessions/SessionList.tsx
import { useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { useAppDispatch, useAppSelector } from "../../store";
import { fetchSessions, setActiveSession } from "../../store/slices/sessionSlice";
import { RunStatusBadge } from "../RunStatusBadge";
import type { RunStatus, SessionSummary } from "../../types";

function sessionStatusToRunStatus(status: string): RunStatus {
  switch (status) {
    case "running": return "Running";
    case "paused":
    case "interrupted": return "Paused";
    case "completed": return "Completed";
    case "failed": return "Failed";
    default: return "NotStarted";
  }
}

interface SessionListProps {
  repoPath: string;
  onResume?: (runId: string) => void;
  /** If non-empty, only sessions with a status in this array are shown. */
  filterStatus?: string[];
  /**
   * If provided, only sessions whose worktree_path matches this value are shown.
   * Pass the empty string "" to show direct-repo sessions (worktree_path === null).
   * Pass null or undefined to disable the filter.
   */
  filterWorktreePath?: string | null;
}

export function SessionList({ repoPath, onResume, filterStatus, filterWorktreePath }: SessionListProps) {
  const dispatch = useAppDispatch();
  const navigate = useNavigate();
  const { sessions, status, selectedRunId } = useAppSelector((s) => s.sessions);

  useEffect(() => {
    if (repoPath) {
      void dispatch(fetchSessions(repoPath));
    }
  }, [dispatch, repoPath]);

  const hasRunningSessions = sessions.some((s) => s.status === "running");

  useEffect(() => {
    if (!repoPath || !hasRunningSessions) return undefined;
    const id = setInterval(() => {
      void dispatch(fetchSessions(repoPath));
    }, 5000);
    return () => clearInterval(id);
  }, [dispatch, repoPath, hasRunningSessions]);

  if (status === "loading") {
    return (
      <div style={{ padding: "24px", color: "var(--text-muted)", fontSize: 13, fontFamily: "var(--font-mono)" }}>
        Loading sessions…
      </div>
    );
  }

  if (sessions.length === 0) {
    return (
      <div className="empty-state">
        <span className="empty-state-icon">◈</span>
        <div className="empty-state-title">No sessions yet</div>
        <div className="empty-state-desc">Start a new session to begin an unattended Ralph workflow.</div>
      </div>
    );
  }

  // Apply client-side filters
  const hasStatusFilter = filterStatus !== undefined && filterStatus.length > 0;
  const hasWorktreeFilter = filterWorktreePath !== undefined && filterWorktreePath !== null;

  const visible = sessions.filter((s) => {
    if (hasStatusFilter && !filterStatus.includes(s.status)) return false;
    if (hasWorktreeFilter) {
      // "" means direct repo (worktree_path === null); otherwise match path
      if (filterWorktreePath === "") {
        if (s.worktree_path !== null) return false;
      } else {
        if (s.worktree_path !== filterWorktreePath) return false;
      }
    }
    return true;
  });

  if (visible.length === 0) {
    return (
      <div className="empty-state">
        <span className="empty-state-icon">◈</span>
        <div className="empty-state-title">No sessions match the selected filters.</div>
        <div className="empty-state-desc">Try clearing the filters to see all sessions.</div>
      </div>
    );
  }

  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 2 }}>
      {visible.map((session) => (
        <SessionRow
          key={session.run_id}
          session={session}
          selected={session.run_id === selectedRunId}
          onSelect={() => {
            dispatch(setActiveSession(session.run_id));
            navigate(`/runs/${session.run_id}`);
          }}
          onResume={
            (session.status === "paused" || session.status === "interrupted") && onResume
              ? () => onResume(session.run_id)
              : undefined
          }
        />
      ))}
    </div>
  );
}

function SessionRow({
  session,
  selected,
  onSelect,
  onResume,
}: {
  session: SessionSummary;
  selected: boolean;
  onSelect: () => void;
  onResume?: () => void;
}) {
  return (
    <div
      role="button"
      tabIndex={0}
      onClick={onSelect}
      onKeyDown={(e) => { if (e.key === "Enter" || e.key === " ") onSelect(); }}
      style={{
        display: "flex",
        alignItems: "center",
        gap: 12,
        padding: "10px 14px",
        borderRadius: "var(--radius-md)",
        background: selected ? "var(--accent-bg)" : "transparent",
        border: selected ? "1px solid var(--accent-dim)30" : "1px solid var(--border-subtle)",
        cursor: "pointer",
        transition: "all var(--transition-fast)",
      }}
      onMouseEnter={(e) => {
        if (!selected) {
          (e.currentTarget as HTMLDivElement).style.background = "var(--bg-elevated)";
          (e.currentTarget as HTMLDivElement).style.borderColor = "var(--border-default)";
        }
      }}
      onMouseLeave={(e) => {
        if (!selected) {
          (e.currentTarget as HTMLDivElement).style.background = "transparent";
          (e.currentTarget as HTMLDivElement).style.borderColor = "var(--border-subtle)";
        }
      }}
    >
      <RunStatusBadge
        status={sessionStatusToRunStatus(session.status)}
        showLabel={false}
        size="sm"
        isDegraded={session.is_degraded === true}
      />
      <div style={{ flex: 1, minWidth: 0 }}>
        <div style={{ fontFamily: "var(--font-mono)", fontSize: 12, color: "var(--text-primary)", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>
          {session.run_id.slice(0, 16)}
        </div>
        <div style={{ fontSize: 11, color: "var(--text-muted)", marginTop: 1 }}>
          {session.description} · {session.created_at}
        </div>
      </div>
      {onResume && (
        <button
          className="btn btn-secondary"
          style={{ padding: "3px 10px", fontSize: 11 }}
          onClick={(e) => { e.stopPropagation(); onResume(); }}
        >
          Resume
        </button>
      )}
      <span style={{ fontSize: 10, color: "var(--text-muted)", flexShrink: 0 }}>›</span>
    </div>
  );
}

// ralph-gui/ui/src/app/components/session-list/session-list.component.ts
import { Component, Input, Output, EventEmitter, inject, effect, computed, ChangeDetectionStrategy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router } from '@angular/router';
import { SessionsService } from '../../services/sessions.service';
import { RunStatusBadgeComponent } from '../run-status-badge/run-status-badge.component';
import type { RunStatus, SessionSummary } from '../../types';

function sessionStatusToRunStatus(status: string): RunStatus {
  switch (status) {
    case 'running': return 'Running';
    case 'paused':
    case 'interrupted': return 'Paused';
    case 'completed': return 'Completed';
    case 'failed': return 'Failed';
    default: return 'NotStarted';
  }
}

@Component({
  selector: 'app-session-list',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [CommonModule, RunStatusBadgeComponent],
  templateUrl: './session-list.component.html',
  styleUrls: ['./session-list.component.css'],
})
export class SessionListComponent {
  readonly sessionsService = inject(SessionsService);
  private readonly router = inject(Router);

  @Input() repoPath = '';
  @Input() filterStatus: string[] = [];
  @Input() filterWorktreePath: string | null | undefined = undefined;
  @Output() resumeRun = new EventEmitter<string>();

  private intervalId: ReturnType<typeof setInterval> | null = null;

  visibleSessions = computed(() => {
    const sessions = this.sessionsService.sessions();
    const hasStatusFilter = this.filterStatus !== undefined && this.filterStatus.length > 0;
    const hasWorktreeFilter = this.filterWorktreePath !== undefined && this.filterWorktreePath !== null;

    return sessions.filter((s) => {
      if (hasStatusFilter && !this.filterStatus.includes(s.status)) return false;
      if (hasWorktreeFilter) {
        if (this.filterWorktreePath === '') {
          if (s.worktree_path !== null) return false;
        } else {
          if (s.worktree_path !== this.filterWorktreePath) return false;
        }
      }
      return true;
    });
  });

  constructor() {
    effect(() => {
      const path = this.repoPath;
      if (path) {
        void this.sessionsService.fetchSessions(path);
      }
    });

    effect((onCleanup) => {
      const path = this.repoPath;
      const sessions = this.sessionsService.sessions();
      const hasRunning = sessions.some(s => s.status === 'running');

      if (path && hasRunning) {
        this.intervalId = setInterval(() => {
          void this.sessionsService.fetchSessions(path);
        }, 5000);
      }

      onCleanup(() => {
        if (this.intervalId) {
          clearInterval(this.intervalId);
          this.intervalId = null;
        }
      });
    });
  }

  sessionStatusToRunStatus = sessionStatusToRunStatus;

  canResume(session: SessionSummary): boolean {
    return session.status === 'paused' || session.status === 'interrupted';
  }

  onSelect(session: SessionSummary): void {
    this.sessionsService.setActiveSession(session.run_id);
    void this.router.navigate(['/runs', session.run_id]);
  }

  onKeyDown(event: KeyboardEvent, session: SessionSummary): void {
    if (event.key === 'Enter' || event.key === ' ') {
      event.preventDefault();
      this.onSelect(session);
    }
  }

  onResumeClick(event: MouseEvent, session: SessionSummary): void {
    event.stopPropagation();
    this.resumeRun.emit(session.run_id);
  }

  onRowHover(event: MouseEvent): void {
    const el = event.currentTarget as HTMLElement;
    if (!el.classList.contains('selected')) {
      el.style.background = 'var(--bg-elevated)';
      el.style.borderColor = 'var(--border-default)';
    }
  }

  onRowLeave(event: MouseEvent): void {
    const el = event.currentTarget as HTMLElement;
    if (!el.classList.contains('selected')) {
      el.style.background = 'transparent';
      el.style.borderColor = 'var(--border-subtle)';
    }
  }
}

@if (sessionsService.status() === 'loading') {
  <div style="padding: 24px; color: var(--text-muted); font-size: 13px; font-family: var(--font-mono);">
    Loading sessions…
  </div>
} @else if (sessionsService.sessions().length === 0) {
  <div class="empty-state">
    <span class="empty-state-icon">◈</span>
    <div class="empty-state-title">No sessions yet</div>
    <div class="empty-state-desc">Start a new session to begin an unattended Ralph workflow.</div>
  </div>
} @else if (visibleSessions().length === 0) {
  <div class="empty-state">
    <span class="empty-state-icon">◈</span>
    <div class="empty-state-title">No sessions match the selected filters.</div>
    <div class="empty-state-desc">Try clearing the filters to see all sessions.</div>
  </div>
} @else {
  <div style="display: flex; flex-direction: column; gap: 2px;">
    @for (session of visibleSessions(); track session.run_id) {
      <div
        role="button"
        tabindex="0"
        (click)="onSelect(session)"
        (keydown)="onKeyDown($event, session)"
        (mouseenter)="onRowHover($event)"
        (mouseleave)="onRowLeave($event)"
        [class.selected]="session.run_id === sessionsService.selectedRunId()"
        style="display: flex; align-items: center; gap: 12px; padding: 10px 14px; border-radius: var(--radius-md); border: 1px solid var(--border-subtle); cursor: pointer; transition: all var(--transition-fast);"
      >
        <app-run-status-badge
          [status]="sessionStatusToRunStatus(session.status)"
          [showLabel]="false"
          size="sm"
          [isDegraded]="session.is_degraded === true"
        />
        <div style="flex: 1; min-width: 0;">
          <div style="font-family: var(--font-mono); font-size: 12px; color: var(--text-primary); overflow: hidden; text-overflow: ellipsis; white-space: nowrap;">
            {{ session.run_id.slice(0, 16) }}
          </div>
          <div style="font-size: 11px; color: var(--text-muted); margin-top: 1px;">
            {{ session.description }} · {{ session.created_at }}
          </div>
        </div>
        @if (canResume(session)) {
          <button
            class="btn btn-secondary"
            style="padding: 3px 10px; font-size: 11px;"
            (click)="onResumeClick($event, session)"
          >
            Resume
          </button>
        }
        <span style="font-size: 10px; color: var(--text-muted); flex-shrink: 0;">›</span>
      </div>
    }
  </div>
}
