// ralph-gui/ui/src/components/sessions/NewSessionWizard.tsx
import { useState, useEffect } from "react";
import { useAppSelector } from "../../store";
import { listAgentProfiles, launchRalphSession, savePromptFile } from "../../api/tauri";
import type { AgentProfile } from "../../types";
import { PreflightSummary } from "./PreflightSummary";
import { PromptTemplatePicker } from "./PromptTemplatePicker";
import { PROMPT_TEMPLATES } from "./promptTemplates";
import { PromptReviewPanel } from "./PromptReviewPanel";

const PRESETS_KEY = "ralph_gui_presets";

interface LaunchPreset {
  name: string;
  developerIterations: number;
  reviewerPasses: number;
  agentProfile: string | null;
}

function loadPresets(): LaunchPreset[] {
  try {
    const raw = localStorage.getItem(PRESETS_KEY);
    if (!raw) return [];
    return JSON.parse(raw) as LaunchPreset[];
  } catch {
    return [];
  }
}

function savePresets(presets: LaunchPreset[]): void {
  localStorage.setItem(PRESETS_KEY, JSON.stringify(presets));
}

type WizardStep = "template" | "config" | "preflight";

interface NewSessionWizardProps {
  onClose: () => void;
  preselectedWorktreePath?: string | null;
}

export function NewSessionWizard({
  onClose,
  preselectedWorktreePath,
}: NewSessionWizardProps) {
  const worktrees = useAppSelector((s) => s.worktrees.worktrees);
  const activePath = useAppSelector((s) => s.worktrees.activeWorktreePath);

  const [step, setStep] = useState<WizardStep>("template");
  const [repoPath, setRepoPath] = useState(
    worktrees.find((wt) => wt.is_main)?.path ?? "",
  );
  const [worktreePath, setWorktreePath] = useState<string | null>(
    preselectedWorktreePath !== undefined ? preselectedWorktreePath : activePath,
  );
  const [promptContent, setPromptContent] = useState(
    PROMPT_TEMPLATES.find((t) => t.id === "feature")?.content ?? "",
  );
  const [developerIterations, setDeveloperIterations] = useState(5);
  const [reviewerPasses, setReviewerPasses] = useState(2);
  const [isLaunching, setIsLaunching] = useState(false);
  const [launchError, setLaunchError] = useState<string | null>(null);
  const [showReviewPanel, setShowReviewPanel] = useState(false);
  const [agentProfiles, setAgentProfiles] = useState<AgentProfile[]>([]);
  const [selectedAgentProfile, setSelectedAgentProfile] = useState<
    string | null
  >(null);

  // Preset state
  const [presets, setPresets] = useState<LaunchPreset[]>(() => loadPresets());
  const [presetNameInput, setPresetNameInput] = useState("");

  // Load agent profiles when repo path is known
  useEffect(() => {
    if (!repoPath) return;
    listAgentProfiles(repoPath)
      .then((profiles) => {
        setAgentProfiles(profiles);
      })
      .catch(() => {
        // Non-fatal: agent profiles are optional
        setAgentProfiles([]);
      });
  }, [repoPath]);

  const promptPath = repoPath ? `${repoPath}/PROMPT.md` : "";

  function handleSavePreset() {
    if (!presetNameInput.trim()) return;
    const updated = [
      ...presets.filter((p) => p.name !== presetNameInput.trim()),
      {
        name: presetNameInput.trim(),
        developerIterations,
        reviewerPasses,
        agentProfile: selectedAgentProfile,
      },
    ];
    savePresets(updated);
    setPresets(updated);
    setPresetNameInput("");
  }

  function handleLoadPreset(name: string) {
    const preset = presets.find((p) => p.name === name);
    if (!preset) return;
    setDeveloperIterations(preset.developerIterations);
    setReviewerPasses(preset.reviewerPasses);
    setSelectedAgentProfile(preset.agentProfile);
  }

  function handleDeletePreset(name: string) {
    const updated = presets.filter((p) => p.name !== name);
    savePresets(updated);
    setPresets(updated);
  }

  function handleTemplateSelect(content: string) {
    setPromptContent(content);
    setStep("config");
  }

  function handleNext() {
    if (!repoPath.trim()) return;
    setStep("preflight");
  }

  async function handleLaunch() {
    setIsLaunching(true);
    setLaunchError(null);
    try {
      // Write the prompt to disk before launching
      if (promptPath) {
        await savePromptFile(promptPath, promptContent);
      }
      const selectedProfile = agentProfiles.find(
        (p) => p.name === selectedAgentProfile,
      );
      await launchRalphSession({
        repo_path: repoPath,
        worktree_path: worktreePath,
        prompt_path: promptPath,
        developer_iterations: developerIterations,
        reviewer_passes: reviewerPasses,
        developer_agent: selectedProfile?.developer_agent ?? null,
        reviewer_agent: selectedProfile?.reviewer_agent ?? null,
      });
      onClose();
    } catch (err) {
      setLaunchError(err instanceof Error ? err.message : "Launch failed");
    } finally {
      setIsLaunching(false);
    }
  }

  if (step === "template") {
    return (
      <div
        data-testid="wizard-template-step"
        style={{ display: "flex", flexDirection: "column", gap: 20 }}
      >
        <PromptTemplatePicker onSelect={handleTemplateSelect} />
        <div style={{ display: "flex", gap: 8, justifyContent: "flex-end" }}>
          <button className="btn btn-ghost" onClick={onClose}>
            Cancel
          </button>
        </div>
      </div>
    );
  }

  if (step === "preflight") {
    return (
      <div style={{ display: "flex", flexDirection: "column", gap: 12 }}>
        {launchError && (
          <div
            data-testid="launch-error"
            style={{
              padding: "8px 12px",
              background: "var(--error-bg, #fee)",
              border: "1px solid var(--error-border, #f99)",
              borderRadius: "var(--radius-md)",
              fontSize: 12,
              color: "var(--error-text, #c00)",
            }}
          >
            {launchError}
          </div>
        )}
        <PreflightSummary
          repoPath={repoPath}
          worktreePath={worktreePath}
          promptPath={promptPath}
          developerIterations={developerIterations}
          reviewerPasses={reviewerPasses}
          onConfirm={() => void handleLaunch()}
          onBack={() => setStep("config")}
          isLaunching={isLaunching}
        />
      </div>
    );
  }

  // Step: config
  return (
    <div
      data-testid="wizard-config-step"
      style={{ display: "flex", flexDirection: "column", gap: 16 }}
    >
      {/* Repo path */}
      <div>
        <label className="section-label" htmlFor="repo-path">
          Repository path
        </label>
        <input
          id="repo-path"
          className="input input-mono"
          value={repoPath}
          onChange={(e) => setRepoPath(e.target.value)}
          placeholder="/path/to/your/repo"
        />
      </div>

      {/* Worktree selection */}
      {worktrees.length > 0 && (
        <div>
          <label className="section-label" htmlFor="worktree-select">
            Context
          </label>
          <select
            id="worktree-select"
            className="input"
            value={worktreePath ?? ""}
            onChange={(e) => setWorktreePath(e.target.value || null)}
            style={{ fontFamily: "var(--font-mono)", fontSize: 12 }}
          >
            <option value="">Direct repository (no worktree)</option>
            {worktrees
              .filter((wt) => !wt.is_main)
              .map((wt) => (
                <option key={wt.path} value={wt.path}>
                  {wt.name} ({wt.branch})
                </option>
              ))}
          </select>
        </div>
      )}

      {/* Agent profile selection */}
      {agentProfiles.length > 0 && (
        <div>
          <label className="section-label" htmlFor="agent-profile">
            Agent profile
          </label>
          <select
            id="agent-profile"
            data-testid="agent-profile-select"
            className="input"
            value={selectedAgentProfile ?? ""}
            onChange={(e) => setSelectedAgentProfile(e.target.value || null)}
            style={{ fontFamily: "var(--font-mono)", fontSize: 12 }}
          >
            <option value="">Default (from config)</option>
            {agentProfiles.map((p) => (
              <option key={p.name} value={p.name}>
                {p.name} — dev: {p.developer_agent} / reviewer:{" "}
                {p.reviewer_agent}
              </option>
            ))}
          </select>
        </div>
      )}

      {/* Preset picker */}
      {presets.length > 0 && (
        <div>
          <label className="section-label">Load preset</label>
          <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
            <select
              data-testid="load-preset-select"
              className="input"
              defaultValue=""
              onChange={(e) => {
                if (e.target.value) handleLoadPreset(e.target.value);
              }}
              style={{ fontFamily: "var(--font-mono)", fontSize: 12 }}
            >
              <option value="">— select a preset —</option>
              {presets.map((p) => (
                <option key={p.name} value={p.name}>
                  {p.name}
                </option>
              ))}
            </select>
          </div>
          {/* Saved preset list with delete buttons */}
          <div style={{ marginTop: 6, display: "flex", flexWrap: "wrap", gap: 6 }}>
            {presets.map((p) => (
              <span
                key={p.name}
                style={{
                  display: "inline-flex",
                  alignItems: "center",
                  gap: 4,
                  padding: "2px 8px",
                  borderRadius: 100,
                  background: "var(--bg-elevated)",
                  border: "1px solid var(--border-subtle)",
                  fontSize: 11,
                  color: "var(--text-secondary)",
                  fontFamily: "var(--font-mono)",
                }}
              >
                {p.name}
                <button
                  data-testid={`delete-preset-${p.name}`}
                  onClick={() => handleDeletePreset(p.name)}
                  style={{
                    background: "none",
                    border: "none",
                    cursor: "pointer",
                    color: "var(--text-muted)",
                    fontSize: 10,
                    padding: 0,
                    lineHeight: 1,
                  }}
                  title={`Delete preset "${p.name}"`}
                >
                  ✕
                </button>
              </span>
            ))}
          </div>
        </div>
      )}

      {/* Iteration config */}
      <div
        style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12 }}
      >
        <div>
          <label className="section-label" htmlFor="dev-iters">
            Dev iterations
          </label>
          <input
            id="dev-iters"
            className="input"
            type="number"
            min={1}
            max={20}
            value={developerIterations}
            onChange={(e) => setDeveloperIterations(Number(e.target.value))}
          />
        </div>
        <div>
          <label className="section-label" htmlFor="rev-passes">
            Review passes
          </label>
          <input
            id="rev-passes"
            className="input"
            type="number"
            min={1}
            max={10}
            value={reviewerPasses}
            onChange={(e) => setReviewerPasses(Number(e.target.value))}
          />
        </div>
      </div>

      {/* Save as preset */}
      <div>
        <label className="section-label">Save current config as preset</label>
        <div style={{ display: "flex", gap: 8 }}>
          <input
            data-testid="preset-name-input"
            className="input input-mono"
            value={presetNameInput}
            onChange={(e) => setPresetNameInput(e.target.value)}
            placeholder="Preset name…"
            style={{ flex: 1 }}
          />
          <button
            data-testid="save-preset-button"
            className="btn btn-secondary"
            onClick={handleSavePreset}
            disabled={!presetNameInput.trim()}
            style={{ flexShrink: 0 }}
          >
            Save
          </button>
        </div>
      </div>

      {/* Prompt editor with optional AI review panel */}
      <div>
        <div
          style={{
            display: "flex",
            justifyContent: "space-between",
            alignItems: "center",
            marginBottom: 6,
          }}
        >
          <label className="section-label" style={{ marginBottom: 0 }}>
            PROMPT.md
          </label>
          <button
            className="btn btn-ghost"
            style={{ fontSize: 11, padding: "2px 10px" }}
            onClick={() => setShowReviewPanel((v) => !v)}
            data-testid="toggle-review-panel"
          >
            {showReviewPanel ? "Hide AI review" : "Review with AI"}
          </button>
        </div>
        <textarea
          id="prompt-editor"
          className="input input-mono"
          rows={10}
          value={promptContent}
          onChange={(e) => setPromptContent(e.target.value)}
          style={{ resize: "vertical", lineHeight: 1.6 }}
        />
        {showReviewPanel && (
          <div style={{ marginTop: 10 }}>
            <PromptReviewPanel
              promptContent={promptContent}
              onApplyImprovedPrompt={(improved) => setPromptContent(improved)}
            />
          </div>
        )}
      </div>

      <div style={{ display: "flex", gap: 8, justifyContent: "flex-end" }}>
        <button
          className="btn btn-ghost"
          onClick={() => setStep("template")}
        >
          ← Templates
        </button>
        <button className="btn btn-ghost" onClick={onClose}>
          Cancel
        </button>
        <button
          className="btn btn-primary"
          onClick={handleNext}
          disabled={!repoPath.trim()}
          data-testid="review-launch-button"
        >
          Review & launch →
        </button>
      </div>
    </div>
  );
}

// ralph-gui/ui/src/app/components/new-session-wizard/new-session-wizard.component.ts
import { Component, Input, Output, EventEmitter, inject, signal, computed, effect, ChangeDetectionStrategy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { WorktreesService } from '../../services/worktrees.service';
import { AgentProfileService } from '../../services/agent-profile.service';
import { TauriService } from '../../services/tauri.service';
import { PreflightSummaryComponent } from '../preflight-summary/preflight-summary.component';
import { PromptTemplatePickerComponent } from '../prompt-template-picker/prompt-template-picker.component';
import { PromptReviewPanelComponent } from '../prompt-review-panel/prompt-review-panel.component';
import { InlineWorktreeCreateComponent } from '../inline-worktree-create/inline-worktree-create.component';
import { StepIndicatorComponent } from './step-indicator.component';

type WizardStep = 'template' | 'config' | 'preflight';

interface LaunchPreset {
  name: string;
  developerIterations: number;
  reviewerPasses: number;
  agentProfile: string | null;
}

const PRESETS_KEY = 'ralph_gui_presets';

function loadPresets(): LaunchPreset[] {
  if (typeof localStorage === 'undefined') return [];
  try {
    const raw = localStorage.getItem(PRESETS_KEY);
    if (!raw) return [];
    return JSON.parse(raw) as LaunchPreset[];
  } catch {
    return [];
  }
}

function savePresets(presets: LaunchPreset[]): void {
  if (typeof localStorage === 'undefined') return;
  localStorage.setItem(PRESETS_KEY, JSON.stringify(presets));
}

@Component({
  selector: 'app-new-session-wizard',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [
    CommonModule,
    PreflightSummaryComponent,
    PromptTemplatePickerComponent,
    PromptReviewPanelComponent,
    InlineWorktreeCreateComponent,
    StepIndicatorComponent,
  ],
  templateUrl: './new-session-wizard.component.html',
})
export class NewSessionWizardComponent {
  readonly worktreesService = inject(WorktreesService);
  readonly agentProfileService = inject(AgentProfileService);
  readonly tauri = inject(TauriService);

  @Input() set repoPathInput(value: string) {
    this.repoPath.set(value);
  }
  @Output() readonly closeWizard = new EventEmitter<void>();
  @Output() readonly sessionLaunched = new EventEmitter<string>();

  readonly step = signal<WizardStep>('template');
  readonly repoPath = signal('');
  readonly worktreePath = signal<string | null>(null);
  readonly promptPath = signal('');
  readonly promptContent = signal('');
  readonly developerIterations = signal(5);
  readonly reviewerPasses = signal(2);
  readonly selectedWorktreePath = signal<string | null>(null);
  readonly selectedAgentProfile = signal<string | null>(null);
  readonly isLaunching = signal(false);
  readonly launchError = signal<string | null>(null);
  readonly presets = signal<LaunchPreset[]>(loadPresets());
  readonly newPresetName = signal('');
  readonly showReviewPanel = signal(false);
  readonly showCreateWorktree = signal(false);

  readonly nonMainWorktrees = computed(() => 
    this.worktreesService.worktrees().filter(wt => !wt.is_main)
  );

  readonly promptService = {
    content: this.promptContent,
  };

  constructor() {
    effect(() => {
      const path = this.repoPath();
      if (path) {
        void this.worktreesService.fetchWorktrees(path);
        void this.agentProfileService.fetchProfiles(path);
      }
    });
  }

  onTemplateSelect(content: string): void {
    this.promptContent.set(content);
    this.step.set('config');
  }

  handleNext(): void {
    const current = this.step();
    if (current === 'template') {
      if (this.promptContent().trim()) {
        this.step.set('config');
      }
    } else if (current === 'config') {
      if (this.repoPath().trim()) {
        this.step.set('preflight');
      }
    }
  }

  onRepoPathInput(event: Event): void {
    const value = (event.target as HTMLInputElement).value;
    this.repoPath.set(value);
  }

  onWorktreeChange(event: Event): void {
    const value = (event.target as HTMLSelectElement).value;
    this.worktreePath.set(value || null);
  }

  onAgentProfileChange(event: Event): void {
    const value = (event.target as HTMLSelectElement).value;
    this.selectedAgentProfile.set(value || null);
  }

  onPresetLoad(event: Event): void {
    const name = (event.target as HTMLSelectElement).value;
    if (!name) return;
    const preset = this.presets().find(p => p.name === name);
    if (preset) {
      this.loadPreset(preset);
    }
  }

  onPresetNameInput(event: Event): void {
    const value = (event.target as HTMLInputElement).value;
    this.newPresetName.set(value);
  }

  toggleCreateWorktree(): void {
    this.showCreateWorktree.update(v => !v);
  }

  onWorktreeCreated(worktree: { path: string }): void {
    this.selectedWorktreePath.set(worktree.path);
    this.showCreateWorktree.set(false);
  }

  onDevItersChange(event: Event): void {
    const value = parseInt((event.target as HTMLInputElement).value, 10);
    if (!isNaN(value) && value > 0) {
      this.developerIterations.set(value);
    }
  }

  onRevPassesChange(event: Event): void {
    const value = parseInt((event.target as HTMLInputElement).value, 10);
    if (!isNaN(value) && value > 0) {
      this.reviewerPasses.set(value);
    }
  }

  onPromptChange(event: Event): void {
    const value = (event.target as HTMLTextAreaElement).value;
    this.promptContent.set(value);
  }

  applyImprovedPrompt(content: string): void {
    this.promptContent.set(content);
  }

  handleLaunch(): void {
    void this.launchSession();
  }

  async launchSession(): Promise<void> {
    if (this.isLaunching()) return;

    this.isLaunching.set(true);
    this.launchError.set(null);
    
    try {
      const promptFileName = `prompt-${Date.now()}.md`;
      const promptPath = `${this.repoPath()}/.ralph/prompts/${promptFileName}`;
      
      await this.tauri.savePromptFile(promptPath, this.promptContent());

      const runId = await this.tauri.launchRalphSession({
        repo_path: this.repoPath(),
        worktree_path: this.selectedWorktreePath(),
        prompt_path: promptPath,
        developer_iterations: this.developerIterations(),
        reviewer_passes: this.reviewerPasses(),
        developer_agent: this.selectedAgentProfile(),
        reviewer_agent: null,
      });

      this.sessionLaunched.emit(runId);
    } catch (e) {
      this.launchError.set(e instanceof Error ? e.message : String(e));
    } finally {
      this.isLaunching.set(false);
    }
  }

  savePreset(): void {
    const name = this.newPresetName().trim();
    if (!name) return;

    const preset: LaunchPreset = {
      name,
      developerIterations: this.developerIterations(),
      reviewerPasses: this.reviewerPasses(),
      agentProfile: this.selectedAgentProfile(),
    };

    const updated = [...this.presets(), preset];
    this.presets.set(updated);
    savePresets(updated);
    this.newPresetName.set('');
  }

  loadPreset(preset: LaunchPreset): void {
    this.developerIterations.set(preset.developerIterations);
    this.reviewerPasses.set(preset.reviewerPasses);
    this.selectedAgentProfile.set(preset.agentProfile);
  }

  deletePreset(name: string): void {
    const updated = this.presets().filter(p => p.name !== name);
    this.presets.set(updated);
    savePresets(updated);
  }
}

<!-- Template Step -->
@if (step() === 'template') {
  <div data-testid="wizard-template-step" style="display: flex; flex-direction: column; gap: 20px;">
    <app-step-indicator [currentStep]="step()" />
    <app-prompt-template-picker (selectTemplate)="onTemplateSelect($event)" />
    <div style="display: flex; gap: 8px; justify-content: flex-end;">
      <button class="btn btn-ghost" (click)="closeWizard.emit()">Cancel</button>
    </div>
  </div>
}

<!-- Preflight Step -->
@if (step() === 'preflight') {
  <div style="display: flex; flex-direction: column; gap: 12px;">
    <app-step-indicator [currentStep]="step()" />
    @if (launchError()) {
      <div
        data-testid="launch-error"
        style="padding: 8px 12px; background: var(--error-bg, #fee); border: 1px solid var(--error-border, #f99); border-radius: var(--radius-md); font-size: 12px; color: var(--error-text, #c00);"
      >
        {{ launchError() }}
      </div>
    }
    <app-preflight-summary
      [repoPath]="repoPath()"
      [worktreePath]="worktreePath()"
      [promptPath]="promptPath()"
      [developerIterations]="developerIterations()"
      [reviewerPasses]="reviewerPasses()"
      [isLaunching]="isLaunching()"
      (confirmLaunch)="handleLaunch()"
      (goBack)="step.set('config')"
    />
  </div>
}

<!-- Config Step -->
@if (step() === 'config') {
  <div data-testid="wizard-config-step" style="display: flex; flex-direction: column; gap: 16px;">
    <app-step-indicator [currentStep]="step()" />

    <!-- Repo path -->
    <div>
      <label class="section-label" for="repo-path">Repository path</label>
      <input
        id="repo-path"
        class="input input-mono"
        [value]="repoPath()"
        (input)="onRepoPathInput($event)"
        placeholder="/path/to/your/repo"
      />
    </div>

    <!-- Worktree selection -->
    @if (worktreesService.worktrees().length > 0) {
      <div>
        <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 6px;">
          <label class="section-label" for="worktree-select" style="margin-bottom: 0;">Context</label>
          <button
            data-testid="create-worktree-toggle"
            class="btn btn-ghost"
            style="font-size: 11px; padding: 2px 10px;"
            (click)="toggleCreateWorktree()"
          >
            {{ showCreateWorktree() ? '← Select existing' : '+ Create new worktree' }}
          </button>
        </div>
        @if (!showCreateWorktree()) {
          <select
            id="worktree-select"
            class="input"
            [value]="worktreePath() ?? ''"
            (change)="onWorktreeChange($event)"
            style="font-family: var(--font-mono); font-size: 12px;"
          >
            <option value="">Direct repository (no worktree)</option>
            @for (wt of nonMainWorktrees(); track wt.path) {
              <option [value]="wt.path">{{ wt.name }} ({{ wt.branch }})</option>
            }
          </select>
        }
        @if (showCreateWorktree()) {
          <app-inline-worktree-create
            [repoPath]="repoPath()"
            (created)="onWorktreeCreated($event)"
          />
        }
      </div>
    }

    <!-- Agent profile selection -->
    @if (agentProfileService.profiles().length > 0) {
      <div>
        <label class="section-label" for="agent-profile">Agent profile</label>
        <select
          id="agent-profile"
          data-testid="agent-profile-select"
          class="input"
          [value]="agentProfileService.selectedProfile() ?? ''"
          (change)="onAgentProfileChange($event)"
          style="font-family: var(--font-mono); font-size: 12px;"
        >
          <option value="">Default (from config)</option>
          @for (p of agentProfileService.profiles(); track p.name) {
            <option [value]="p.name">{{ p.name }} — dev: {{ p.developer_agent }} / reviewer: {{ p.reviewer_agent }}</option>
          }
        </select>
      </div>
    }

    <!-- Preset picker -->
    @if (presets().length > 0) {
      <div>
        <label class="section-label">Load preset</label>
        <div style="display: flex; align-items: center; gap: 8px;">
          <select
            data-testid="load-preset-select"
            class="input"
            (change)="onPresetLoad($event)"
            style="font-family: var(--font-mono); font-size: 12px;"
          >
            <option value="">— select a preset —</option>
            @for (p of presets(); track p.name) {
              <option [value]="p.name">{{ p.name }}</option>
            }
          </select>
        </div>
        <!-- Saved preset list with delete buttons -->
        <div style="margin-top: 6px; display: flex; flex-wrap: wrap; gap: 6px;">
          @for (p of presets(); track p.name) {
            <span style="display: inline-flex; align-items: center; gap: 4px; padding: 2px 8px; border-radius: 100px; background: var(--bg-elevated); border: 1px solid var(--border-subtle); font-size: 11px; color: var(--text-secondary); font-family: var(--font-mono);">
              {{ p.name }}
              <button
                [attr.data-testid]="'delete-preset-' + p.name"
                (click)="deletePreset(p.name)"
                style="background: none; border: none; cursor: pointer; color: var(--text-muted); font-size: 10px; padding: 0; line-height: 1;"
                [title]="'Delete preset ' + p.name + ''"
              >
                ✕
              </button>
            </span>
          }
        </div>
      </div>
    }

    <!-- Iteration config -->
    <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 12px;">
      <div>
        <label class="section-label" for="dev-iters">Dev iterations</label>
        <input
          id="dev-iters"
          class="input"
          type="number"
          min="1"
          max="20"
          [value]="developerIterations()"
          (input)="onDevItersChange($event)"
        />
      </div>
      <div>
        <label class="section-label" for="rev-passes">Review passes</label>
        <input
          id="rev-passes"
          class="input"
          type="number"
          min="1"
          max="10"
          [value]="reviewerPasses()"
          (input)="onRevPassesChange($event)"
        />
      </div>
    </div>

    <!-- Save as preset -->
    <div>
      <label class="section-label">Save current config as preset</label>
      <div style="display: flex; gap: 8px;">
        <input
          data-testid="preset-name-input"
          class="input input-mono"
          [value]="presetNameInput()"
          (input)="onPresetNameInput($event)"
          placeholder="Preset name…"
          style="flex: 1;"
        />
        <button
          data-testid="save-preset-button"
          class="btn btn-secondary"
          (click)="savePreset()"
          [disabled]="!presetNameInput().trim()"
          style="flex-shrink: 0;"
        >
          Save
        </button>
      </div>
    </div>

    <!-- Prompt editor with optional AI review panel -->
    <div>
      <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 6px;">
        <label class="section-label" style="margin-bottom: 0;">PROMPT.md</label>
        <button
          class="btn btn-ghost"
          style="font-size: 11px; padding: 2px 10px;"
          (click)="showReviewPanel.set(!showReviewPanel())"
          data-testid="toggle-review-panel"
        >
          {{ showReviewPanel() ? 'Hide AI review' : 'Review with AI' }}
        </button>
      </div>
      <textarea
        id="prompt-editor"
        class="input input-mono"
        rows="10"
        [value]="promptService.content()"
        (input)="onPromptChange($event)"
        style="resize: vertical; line-height: 1.6;"
      ></textarea>
      @if (showReviewPanel()) {
        <div style="margin-top: 10px;">
          <app-prompt-review-panel
            [promptContent]="promptService.content()"
            (applyImprovedPrompt)="applyImprovedPrompt($event)"
          />
        </div>
      }
    </div>

    <div style="display: flex; gap: 8px; justify-content: flex-end;">
      <button class="btn btn-ghost" (click)="step.set('template')">← Templates</button>
      <button class="btn btn-ghost" (click)="closeWizard.emit()">Cancel</button>
      <button
        class="btn btn-primary"
        (click)="handleNext()"
        [disabled]="!repoPath().trim()"
        data-testid="review-launch-button"
      >
        Review & launch →
      </button>
    </div>
  </div>
}
