// ralph-gui/ui/src/pages/Home.tsx
import { useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { useAppDispatch, useAppSelector } from "../store";
import { fetchWorktrees } from "../store/slices/worktreeSlice";
import { fetchResumableRuns } from "../store/slices/runSlice";
import { RunStatusBadge } from "../components/RunStatusBadge";
import { RepoSelector } from "../components/RepoSelector";

export function Home() {
  const dispatch = useAppDispatch();
  const navigate = useNavigate();
  const worktrees = useAppSelector((s) => s.worktrees.worktrees);
  const resumableRuns = useAppSelector((s) => s.runs.resumableRuns);
  const mainWorktree = worktrees.find((wt) => wt.is_main);

  useEffect(() => {
    if (mainWorktree) {
      void dispatch(fetchResumableRuns(mainWorktree.path));
    }
  }, [dispatch, mainWorktree]);

  useEffect(() => {
    if (mainWorktree) {
      void dispatch(fetchWorktrees(mainWorktree.path));
    }
  }, [dispatch, mainWorktree]);

  const hasContent = worktrees.length > 0 || resumableRuns.length > 0;

  if (!hasContent) {
    return (
      <div className="page-content" style={{ display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center" }}>
        <div style={{ maxWidth: 480, textAlign: "center", animation: "fadeIn 300ms ease" }}>
          <div style={{ fontSize: 48, marginBottom: 16, opacity: 0.2 }}>◈</div>
          <h1 style={{ fontFamily: "var(--font-display)", fontSize: 24, fontWeight: 600, color: "var(--text-primary)", letterSpacing: "-0.02em", marginBottom: 8 }}>
            Welcome to Ralph Workflow
          </h1>
          <p style={{ fontSize: 14, color: "var(--text-secondary)", lineHeight: 1.6, marginBottom: 24 }}>
            An unattended AI orchestration platform for long-running development and review cycles.
          </p>
          <div style={{ textAlign: "left", marginBottom: 16 }}>
            <div style={{ fontSize: 12, color: "var(--text-muted)", fontFamily: "var(--font-mono)", marginBottom: 8 }}>
              Enter your repository path to get started:
            </div>
            <RepoSelector onRepoSelected={() => void navigate("/")} />
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="page-content">
      <h1 className="page-title" style={{ animation: "fadeIn 200ms ease" }}>Home</h1>

      <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 16, marginBottom: 24, animation: "fadeIn 200ms ease 40ms both" }}>
        <StatCard label="Active worktrees" value={worktrees.filter((wt) => !wt.is_main).length} />
        <StatCard label="Resumable runs" value={resumableRuns.length} accent={resumableRuns.length > 0} />
      </div>

      {resumableRuns.length > 0 && (
        <section style={{ marginBottom: 24, animation: "fadeIn 200ms ease 80ms both" }}>
          <div className="section-label">Interrupted runs — action needed</div>
          <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
            {resumableRuns.map((run) => (
              <div
                key={run.run_id}
                className="card card-elevated"
                style={{ display: "flex", alignItems: "center", gap: 12, padding: "12px 16px" }}
              >
                <RunStatusBadge status="Paused" showLabel={false} isDegraded={run.is_degraded} />
                <div style={{ flex: 1, minWidth: 0 }}>
                  <div style={{ fontFamily: "var(--font-mono)", fontSize: 12, color: "var(--text-primary)" }}>
                    {run.run_id.slice(0, 16)}
                  </div>
                  <div style={{ fontSize: 11, color: "var(--text-muted)" }}>
                    {run.current_phase} · {run.agent_profile}
                  </div>
                </div>
                <button className="btn btn-secondary" style={{ fontSize: 12 }} onClick={() => void navigate(`/runs/${run.run_id}`)}>
                  View
                </button>
              </div>
            ))}
          </div>
        </section>
      )}

      <section style={{ animation: "fadeIn 200ms ease 120ms both" }}>
        <div className="section-label" style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
          <span>Quick actions</span>
        </div>
        <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10 }}>
          <QuickAction icon="▶" label="New session" desc="Start an unattended run" onClick={() => void navigate("/sessions")} />
          <QuickAction icon="⎇" label="Worktrees" desc="Manage git worktrees" onClick={() => void navigate("/worktrees")} />
        </div>
      </section>
    </div>
  );
}

function StatCard({ label, value, accent = false }: { label: string; value: number; accent?: boolean }) {
  return (
    <div className="card" style={{ padding: "16px 20px" }}>
      <div style={{ fontFamily: "var(--font-display)", fontSize: 28, fontWeight: 600, color: accent ? "var(--accent)" : "var(--text-primary)", letterSpacing: "-0.02em" }}>
        {value}
      </div>
      <div style={{ fontSize: 12, color: "var(--text-muted)", marginTop: 2 }}>{label}</div>
    </div>
  );
}

function QuickAction({ icon, label, desc, onClick }: { icon: string; label: string; desc: string; onClick: () => void }) {
  return (
    <button
      onClick={onClick}
      className="card"
      style={{ display: "flex", alignItems: "flex-start", gap: 12, padding: "14px 16px", cursor: "pointer", background: "var(--bg-surface)", border: "1px solid var(--border-subtle)", textAlign: "left", width: "100%" }}
      onMouseEnter={(e) => { (e.currentTarget as HTMLButtonElement).style.borderColor = "var(--border-default)"; }}
      onMouseLeave={(e) => { (e.currentTarget as HTMLButtonElement).style.borderColor = "var(--border-subtle)"; }}
    >
      <span style={{ fontSize: 18, color: "var(--accent)", flexShrink: 0, marginTop: 1 }}>{icon}</span>
      <div>
        <div style={{ fontSize: 13, fontWeight: 500, color: "var(--text-primary)" }}>{label}</div>
        <div style={{ fontSize: 11, color: "var(--text-muted)", marginTop: 2 }}>{desc}</div>
      </div>
    </button>
  );
}

// ralph-gui/ui/src/app/pages/home/home.component.ts
import { Component, inject, effect, computed, ChangeDetectionStrategy } from '@angular/core';
import { Router, RouterModule } from '@angular/router';
import { CommonModule } from '@angular/common';
import { WorktreesService } from '../../services/worktrees.service';
import { RunsService } from '../../services/runs.service';
import { RunStatusBadgeComponent } from '../../components/run-status-badge/run-status-badge.component';
import { RepoSelectorComponent } from '../../components/repo-selector/repo-selector.component';
import { StatCardComponent } from './stat-card.component';
import { QuickActionComponent } from './quick-action.component';

@Component({
  selector: 'app-home',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [
    CommonModule,
    RouterModule,
    RunStatusBadgeComponent,
    RepoSelectorComponent,
    StatCardComponent,
    QuickActionComponent,
  ],
  templateUrl: './home.component.html',
  styles: [`
    :host {
      display: block;
    }
  `],
})
export class HomeComponent {
  readonly worktreesService = inject(WorktreesService);
  readonly runsService = inject(RunsService);
  private readonly router = inject(Router);

  readonly mainWorktree = computed(() =>
    this.worktreesService.worktrees().find(wt => wt.is_main)
  );

  readonly hasContent = computed(() =>
    this.worktreesService.worktrees().length > 0 || this.runsService.resumableRuns().length > 0
  );

  readonly activeWorktreeCount = computed(() =>
    this.worktreesService.worktrees().filter(wt => !wt.is_main).length
  );

  readonly resumableRunsCount = computed(() =>
    this.runsService.resumableRuns().length
  );

  readonly resumableRunsWithShortId = computed(() =>
    this.runsService.resumableRuns().map(run => ({
      ...run,
      run_id_short: run.run_id.substring(0, 16),
    }))
  );

  get hasContentValue(): boolean { return this.hasContent(); }
  get activeWorktreeCountValue(): number { return this.activeWorktreeCount(); }
  get resumableRunsCountValue(): number { return this.resumableRunsCount(); }
  get resumableRuns() { return this.resumableRunsWithShortId(); }

  constructor() {
    effect(() => {
      const main = this.mainWorktree();
      if (main) {
        void this.runsService.fetchResumableRuns(main.path);
        void this.worktreesService.fetchWorktrees(main.path);
      }
    });
  }

  onRepoSelected(): void {
    void this.router.navigate(['/']);
  }

  navigateToRun(runId: string): void {
    void this.router.navigate(['/runs', runId]);
  }

  navigateToSessions(): void {
    void this.router.navigate(['/sessions']);
  }

  navigateToWorktrees(): void {
    void this.router.navigate(['/worktrees']);
  }
}

@if (!hasContentValue) {
  <div class="page-content" style="display: flex; flex-direction: column; align-items: center; justify-content: center;">
    <div style="max-width: 480px; text-align: center; animation: fadeIn 300ms ease;">
      <div style="font-size: 40px; margin-bottom: 20px; opacity: 0.15; font-family: var(--font-mono); color: var(--accent); letter-spacing: -0.05em;">◈</div>
      <h1 style="font-family: var(--font-display); font-size: 24px; font-weight: 600; color: var(--text-primary); letter-spacing: -0.02em; margin-bottom: 10px;">
        Welcome to Ralph Workflow
      </h1>
      <p style="font-size: 13px; color: var(--text-secondary); line-height: 1.7; margin-bottom: 28px;">
        An unattended AI orchestration platform for long-running development and review cycles.
      </p>
      <div style="text-align: left; margin-bottom: 16px;">
        <div style="font-size: 11px; color: var(--text-muted); font-family: var(--font-mono); margin-bottom: 8px; text-transform: uppercase; letter-spacing: 0.06em;">
          Enter your repository path to get started
        </div>
        <app-repo-selector (repoSelected)="onRepoSelected()" />
      </div>
    </div>
  </div>
} @else {
  <div class="page-content">
    <h1 class="page-title" style="animation: fadeIn 200ms ease;">Home</h1>

    <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 16px; margin-bottom: 24px; animation: fadeIn 200ms ease 40ms both;">
      <app-stat-card label="Active worktrees" [value]="activeWorktreeCountValue" />
      <app-stat-card label="Resumable runs" [value]="resumableRunsCountValue" [accent]="resumableRunsCountValue > 0" />
    </div>

    @if (resumableRunsCountValue > 0) {
      <section style="margin-bottom: 24px; animation: fadeIn 200ms ease 80ms both;">
        <div class="section-label">Interrupted runs — action needed</div>
        <div style="display: flex; flex-direction: column; gap: 8px;">
          @for (run of resumableRuns; track run.run_id) {
            <div class="card card-elevated" style="display: flex; align-items: center; gap: 12px; padding: 12px 16px;">
              <app-run-status-badge status="Paused" [showLabel]="false" [isDegraded]="run.is_degraded ?? false" />
              <div style="flex: 1; min-width: 0;">
                <div style="font-family: var(--font-mono); font-size: 12px; color: var(--text-primary);">
                  {{ run.run_id_short }}
                </div>
                <div style="font-size: 11px; color: var(--text-muted);">
                  {{ run.current_phase }} · {{ run.agent_profile }}
                </div>
              </div>
              <button class="btn btn-secondary" style="font-size: 12px;" (click)="navigateToRun(run.run_id)">
                View
              </button>
            </div>
          }
        </div>
      </section>
    }

    <section style="animation: fadeIn 200ms ease 120ms both;">
      <div class="section-label" style="display: flex; justify-content: space-between; align-items: center;">
        <span>Quick actions</span>
      </div>
      <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 10px;">
        <app-quick-action icon="▶" label="New session" desc="Start an unattended run" (action)="navigateToSessions()" />
        <app-quick-action icon="⎇" label="Worktrees" desc="Manage git worktrees" (action)="navigateToWorktrees()" />
      </div>
    </section>
  </div>
}
