// ralph-gui/ui/src/pages/Configuration.tsx
import { useEffect, useRef, useState } from "react";
import { useAppSelector, useAppDispatch } from "../store";
import {
  fetchGlobalConfig,
  fetchEffectiveConfig,
  fetchAiApiKey,
  saveAiApiKeyThunk,
  resetAiApiKeySaveStatus,
  setDirty,
} from "../store/slices/configSlice";
import {
  saveGlobalConfig,
  saveProjectConfig,
  getRawGlobalConfigToml,
  getRawProjectConfigToml,
  validateConfigToml,
} from "../api/tauri";
import type { ConfigView } from "../types";

type TabId = "effective" | "global" | "project";

interface ConfigFieldProps {
  label: string;
  description: string;
  value: string | number | boolean;
}

function ConfigField({ label, description, value }: ConfigFieldProps) {
  const displayValue =
    typeof value === "boolean" ? (value ? "true" : "false") : String(value);
  return (
    <div
      style={{
        display: "flex",
        alignItems: "flex-start",
        justifyContent: "space-between",
        padding: "10px 0",
        borderBottom: "1px solid var(--border-subtle)",
      }}
    >
      <div style={{ flex: 1 }}>
        <div
          style={{
            fontFamily: "var(--font-mono)",
            fontSize: 13,
            color: "var(--text-primary)",
            marginBottom: 2,
          }}
        >
          {label}
        </div>
        <div
          style={{
            fontSize: 11,
            color: "var(--text-muted)",
          }}
        >
          {description}
        </div>
      </div>
      <div
        style={{
          fontFamily: "var(--font-mono)",
          fontSize: 13,
          color:
            typeof value === "boolean"
              ? value
                ? "var(--status-completed)"
                : "var(--text-muted)"
              : "var(--accent)",
          marginLeft: 24,
          flexShrink: 0,
        }}
      >
        {displayValue}
      </div>
    </div>
  );
}

function ConfigTable({ config }: { config: ConfigView }) {
  return (
    <div>
      <ConfigField
        label="verbosity"
        description="Log verbosity level (0=quiet, 1=normal, 2=verbose)"
        value={config.verbosity}
      />
      <ConfigField
        label="developer_iters"
        description="Number of developer agent iterations per cycle"
        value={config.developer_iters}
      />
      <ConfigField
        label="reviewer_reviews"
        description="Number of reviewer passes per cycle"
        value={config.reviewer_reviews}
      />
      <ConfigField
        label="max_dev_continuations"
        description="Maximum continuation budget for developer agent"
        value={config.max_dev_continuations}
      />
      <ConfigField
        label="review_depth"
        description="Depth of reviewer analysis (shallow | standard | deep)"
        value={config.review_depth}
      />
      <ConfigField
        label="checkpoint_enabled"
        description="Persist pipeline state for --resume support"
        value={config.checkpoint_enabled}
      />
      <ConfigField
        label="isolation_mode"
        description="Run agents in isolated environment"
        value={config.isolation_mode}
      />
      <ConfigField
        label="interactive"
        description="Pause for user confirmation between phases"
        value={config.interactive}
      />
    </div>
  );
}

interface TomlEditorProps {
  label: string;
  repoPath: string | null;
  scope: "global" | "project";
}

const DEFAULT_TOML_TEMPLATE = (label: string) =>
  `# ${label} configuration (TOML)\n# Edit values below and save.\n\n[defaults]\n`;

const VALIDATION_DEBOUNCE_MS = 300;

function TomlEditor({ label, repoPath, scope }: TomlEditorProps) {
  const dispatch = useAppDispatch();
  const [toml, setToml] = useState(DEFAULT_TOML_TEMPLATE(label));
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [saveMsg, setSaveMsg] = useState<string | null>(null);
  const [saveError, setSaveError] = useState<string | null>(null);
  const [validationError, setValidationError] = useState<string | null>(null);
  const debounceTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  // Tracks the last successfully fetched TOML so Revert can restore it.
  const savedTomlRef = useRef<string>(DEFAULT_TOML_TEMPLATE(label));

  useEffect(() => {
    setLoading(true);
    const fetchToml = async () => {
      try {
        let content: string;
        if (scope === "global") {
          content = await getRawGlobalConfigToml();
        } else if (repoPath) {
          content = await getRawProjectConfigToml(repoPath);
        } else {
          content = "";
        }
        const resolved = content.length > 0 ? content : DEFAULT_TOML_TEMPLATE(label);
        setToml(resolved);
        savedTomlRef.current = resolved;
      } catch {
        const fallback = DEFAULT_TOML_TEMPLATE(label);
        setToml(fallback);
        savedTomlRef.current = fallback;
      } finally {
        setLoading(false);
      }
    };
    void fetchToml();
  }, [scope, repoPath, label]);

  // Validate TOML on every change, debounced to avoid spamming the backend.
  useEffect(() => {
    if (debounceTimerRef.current !== null) {
      clearTimeout(debounceTimerRef.current);
    }
    debounceTimerRef.current = setTimeout(() => {
      void validateConfigToml(toml).then((error) => {
        setValidationError(error ?? null);
      });
    }, VALIDATION_DEBOUNCE_MS);
    return () => {
      if (debounceTimerRef.current !== null) {
        clearTimeout(debounceTimerRef.current);
      }
    };
  }, [toml]);

  const handleSave = async () => {
    if (scope === "project" && !repoPath) return;
    if (validationError !== null) return;
    setSaving(true);
    setSaveMsg(null);
    setSaveError(null);
    try {
      if (scope === "global") {
        await saveGlobalConfig(toml);
        void dispatch(fetchGlobalConfig());
      } else if (repoPath) {
        await saveProjectConfig(repoPath, toml);
        void dispatch(fetchEffectiveConfig(repoPath));
      }
      savedTomlRef.current = toml;
      setSaveMsg("Saved successfully.");
      dispatch(setDirty(false));
    } catch (e: unknown) {
      setSaveError(e instanceof Error ? e.message : String(e));
    } finally {
      setSaving(false);
    }
  };

  const handleRevert = () => {
    setToml(savedTomlRef.current);
    setValidationError(null);
    dispatch(setDirty(false));
  };

  const scopeLabel = scope === "global" ? "global" : "project";
  const isSaveDisabled = saving || (scope === "project" && !repoPath) || validationError !== null;

  return (
    <div>
      {loading && (
        <div
          style={{
            padding: "8px 0",
            fontSize: 11,
            color: "var(--text-muted)",
            fontFamily: "var(--font-mono)",
          }}
        >
          Loading...
        </div>
      )}
      <textarea
        className="form-input input-mono"
        value={toml}
        onChange={(e) => {
          setToml(e.target.value);
          dispatch(setDirty(true));
        }}
        style={{
          minHeight: 220,
          padding: "12px 14px",
          resize: "vertical",
          lineHeight: 1.7,
          fontSize: 12,
          borderColor: validationError ? "var(--status-failed)" : undefined,
          background: "var(--bg-base, #0d0d0d)",
          color: "var(--text-primary)",
        }}
        spellCheck={false}
      />
      {/* Inline validation error */}
      {validationError && (
        <div
          data-testid="toml-validation-error"
          style={{
            marginTop: 6,
            padding: "6px 10px",
            background: "rgba(248, 81, 73, 0.08)",
            border: "1px solid rgba(248, 81, 73, 0.25)",
            borderRadius: "var(--radius-md)",
            fontSize: 11,
            color: "var(--status-failed)",
            fontFamily: "var(--font-mono)",
          }}
        >
          {validationError}
        </div>
      )}
      <div
        style={{
          display: "flex",
          alignItems: "center",
          gap: 12,
          marginTop: 10,
        }}
      >
        <button
          className="btn btn-primary"
          onClick={() => void handleSave()}
          disabled={isSaveDisabled}
        >
          {saving ? "Saving..." : "Save"}
        </button>
        <button
          className="btn btn-ghost"
          data-testid="revert-config-button"
          onClick={handleRevert}
          disabled={toml === savedTomlRef.current}
          title="Discard unsaved changes and reload from saved state"
        >
          Revert
        </button>
        {/* Scope badge — persistent label so users know which scope they are editing */}
        <span
          data-testid="scope-badge"
          className="chip-mono"
          style={{
            fontSize: 10,
            color: "var(--text-muted)",
            textTransform: "uppercase",
            letterSpacing: "0.08em",
          }}
        >
          {scopeLabel}
        </span>
        {saveMsg && (
          <span
            style={{
              fontSize: 12,
              color: "var(--status-completed)",
              fontFamily: "var(--font-mono)",
            }}
          >
            {saveMsg}
          </span>
        )}
        {saveError && (
          <span
            style={{
              fontSize: 12,
              color: "var(--status-failed)",
              fontFamily: "var(--font-mono)",
            }}
          >
            {saveError}
          </span>
        )}
      </div>
    </div>
  );
}

/// AI Integration section shown in the Global tab.
/// Allows users to persist their Anthropic API key without touching CLI environment variables.
function AiIntegrationSection() {
  const dispatch = useAppDispatch();
  const aiApiKey = useAppSelector((s) => s.config.aiApiKey);
  const saveStatus = useAppSelector((s) => s.config.aiApiKeySaveStatus);
  const aiApiKeyError = useAppSelector((s) => s.config.aiApiKeyError);

  const [localKey, setLocalKey] = useState("");
  const [showKey, setShowKey] = useState(false);

  // Load saved key on mount
  useEffect(() => {
    void dispatch(fetchAiApiKey());
  }, [dispatch]);

  // Sync local input when the store key changes (e.g., loaded from backend)
  useEffect(() => {
    setLocalKey(aiApiKey);
  }, [aiApiKey]);

  // Auto-reset save status after 3 seconds so the success message fades
  useEffect(() => {
    if (saveStatus === "saved") {
      const timer = setTimeout(() => {
        dispatch(resetAiApiKeySaveStatus());
      }, 3000);
      return () => {
        clearTimeout(timer);
      };
    }
    return undefined;
  }, [dispatch, saveStatus]);

  const handleSave = () => {
    void dispatch(saveAiApiKeyThunk(localKey));
  };

  return (
    <div
      style={{
        marginTop: "var(--space-6)",
        paddingTop: "var(--space-6)",
        borderTop: "1px solid var(--border-subtle)",
      }}
    >
      {/* Section heading */}
      <div
        style={{
          fontFamily: "var(--font-display)",
          fontSize: 13,
          fontWeight: 600,
          color: "var(--text-secondary)",
          textTransform: "uppercase",
          letterSpacing: "0.08em",
          marginBottom: "var(--space-3)",
        }}
      >
        AI Integration
      </div>

      <div
        style={{
          fontSize: 11,
          color: "var(--text-muted)",
          fontFamily: "var(--font-mono)",
          marginBottom: "var(--space-4)",
        }}
      >
        Anthropic API key used for AI-assisted PROMPT.md review. Stored at{" "}
        <span style={{ color: "var(--text-secondary)" }}>~/.config/ralph-gui.toml</span>{" "}
        with restricted permissions (0600).
      </div>

      {/* Key input with show/hide toggle */}
      <div
        style={{
          display: "flex",
          alignItems: "center",
          gap: "var(--space-2)",
          marginBottom: "var(--space-3)",
        }}
      >
        <input
          type={showKey ? "text" : "password"}
          className="form-input input-mono"
          value={localKey}
          onChange={(e) => {
            setLocalKey(e.target.value);
          }}
          placeholder="Enter Anthropic API key (sk-ant-...)"
          style={{ flex: 1 }}
        />
        <button
          className="btn btn-ghost"
          onClick={() => {
            setShowKey((prev) => !prev);
          }}
          style={{ flexShrink: 0, minWidth: 52 }}
        >
          {showKey ? "Hide" : "Show"}
        </button>
      </div>

      {/* Save button + feedback */}
      <div
        style={{
          display: "flex",
          alignItems: "center",
          gap: "var(--space-3)",
        }}
      >
        <button
          className="btn btn-primary"
          onClick={handleSave}
          disabled={saveStatus === "saving"}
        >
          {saveStatus === "saving" ? "Saving..." : "Save API Key"}
        </button>
        {saveStatus === "saved" && (
          <span
            style={{
              fontSize: 12,
              color: "var(--status-completed)",
              fontFamily: "var(--font-mono)",
            }}
          >
            Saved
          </span>
        )}
        {saveStatus === "failed" && aiApiKeyError && (
          <span
            style={{
              fontSize: 12,
              color: "var(--status-failed)",
              fontFamily: "var(--font-mono)",
            }}
          >
            {aiApiKeyError}
          </span>
        )}
      </div>
    </div>
  );
}

export function Configuration() {
  const dispatch = useAppDispatch();
  const globalConfig = useAppSelector((s) => s.config.globalConfig);
  const effectiveConfig = useAppSelector((s) => s.config.effectiveConfig);
  const globalStatus = useAppSelector((s) => s.config.globalStatus);
  const worktrees = useAppSelector((s) => s.worktrees.worktrees);
  const activePath = useAppSelector((s) => s.worktrees.activeWorktreePath);
  const mainWorktree = worktrees.find((wt) => wt.is_main);
  const repoPath = activePath ?? mainWorktree?.path ?? null;

  const [activeTab, setActiveTab] = useState<TabId>("effective");

  useEffect(() => {
    void dispatch(fetchGlobalConfig());
  }, [dispatch]);

  useEffect(() => {
    if (repoPath) {
      void dispatch(fetchEffectiveConfig(repoPath));
    }
  }, [dispatch, repoPath]);

  const tabs: { id: TabId; label: string }[] = [
    { id: "effective", label: "Effective" },
    { id: "global", label: "Global" },
    { id: "project", label: "Project" },
  ];

  const displayConfig: ConfigView | null =
    activeTab === "effective" ? (effectiveConfig ?? globalConfig) : null;

  return (
    <div className="page-content">
      {/* Header */}
      <div
        style={{
          display: "flex",
          alignItems: "center",
          justifyContent: "space-between",
          marginBottom: "var(--space-6)",
          animation: "fadeIn 200ms ease",
        }}
      >
        <h1 className="page-title" style={{ marginBottom: 0 }}>
          Configuration
        </h1>
        {repoPath && (
          <span className="chip-mono" style={{ fontSize: 11 }}>
            {repoPath}
          </span>
        )}
      </div>

      <div style={{ animation: "fadeIn 200ms ease 40ms both" }}>
        {/* Tab bar */}
        <div className="tab-bar" style={{ marginBottom: "var(--space-5)" }}>
          {tabs.map((tab) => (
            <button
              key={tab.id}
              className={`tab-item${activeTab === tab.id ? " tab-item--active" : ""}`}
              onClick={() => {
                setActiveTab(tab.id);
              }}
            >
              {tab.label}
            </button>
          ))}
        </div>

        {/* Effective read view */}
        {activeTab === "effective" && (
          <div className="card">
            <div
              style={{
                marginBottom: 12,
                fontSize: 11,
                color: "var(--text-muted)",
                fontFamily: "var(--font-mono)",
              }}
            >
              Merged view: project overrides global defaults
            </div>

            {globalStatus === "loading" && (
              <div
                style={{
                  padding: "var(--space-6)",
                  textAlign: "center",
                  color: "var(--text-muted)",
                  fontSize: 13,
                  fontFamily: "var(--font-mono)",
                }}
              >
                Loading...
              </div>
            )}

            {displayConfig ? (
              <ConfigTable config={displayConfig} />
            ) : globalStatus !== "loading" ? (
              <div
                style={{
                  padding: "var(--space-6)",
                  textAlign: "center",
                  color: "var(--text-muted)",
                  fontSize: 13,
                  fontFamily: "var(--font-mono)",
                }}
              >
                {!repoPath
                  ? "Select a repository to see effective config."
                  : "No configuration loaded."}
              </div>
            ) : null}
          </div>
        )}

        {/* Global edit view */}
        {activeTab === "global" && (
          <div className="card">
            <div
              style={{
                marginBottom: 16,
                fontSize: 11,
                color: "var(--text-muted)",
                fontFamily: "var(--font-mono)",
              }}
            >
              Global config stored at{" "}
              <span style={{ color: "var(--text-secondary)" }}>
                ~/.config/ralph-workflow.toml
              </span>
            </div>
            <TomlEditor label="Global" repoPath={null} scope="global" />
            <AiIntegrationSection />
          </div>
        )}

        {/* Project edit view */}
        {activeTab === "project" && (
          <div className="card">
            <div
              style={{
                marginBottom: 16,
                fontSize: 11,
                color: "var(--text-muted)",
                fontFamily: "var(--font-mono)",
              }}
            >
              Project-level config stored at{" "}
              <span style={{ color: "var(--text-secondary)" }}>
                {repoPath ? `${repoPath}/.ralph/config.toml` : "<repo>/.ralph/config.toml"}
              </span>
            </div>
            {!repoPath && (
              <div
                style={{
                  padding: "10px 12px",
                  background: "rgba(232,168,56,0.08)",
                  border: "1px solid rgba(232,168,56,0.2)",
                  borderRadius: "var(--radius-md)",
                  color: "var(--accent)",
                  fontSize: 12,
                  fontFamily: "var(--font-mono)",
                  marginBottom: 12,
                }}
              >
                Select a repository context to edit project config.
              </div>
            )}
            <TomlEditor label="Project" repoPath={repoPath} scope="project" />
          </div>
        )}
      </div>
    </div>
  );
}

// ralph-gui/ui/src/app/pages/configuration/configuration.component.ts
import { Component, inject, signal, effect, computed, input, ChangeDetectionStrategy, forwardRef } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ConfigService } from '../../services/config.service';
import { WorktreesService } from '../../services/worktrees.service';
import { TauriService } from '../../services/tauri.service';
import type { ConfigView } from '../../types';

type TabId = 'effective' | 'global' | 'project';

const DEFAULT_TOML_TEMPLATE = (label: string) =>
  `# ${label} configuration (TOML)\n# Edit values below and save.\n\n[defaults]\n`;

const VALIDATION_DEBOUNCE_MS = 300;

@Component({
  selector: 'app-configuration',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [
    CommonModule,
    forwardRef(() => ConfigTableComponent),
    forwardRef(() => TomlEditorComponent),
    forwardRef(() => AiIntegrationSectionComponent),
  ],
  template: `
    <div class="page-content">
      <!-- Header -->
      <div style="display: flex; align-items: center; justify-content: space-between; margin-bottom: var(--space-6); animation: fadeIn 200ms ease;">
        <h1 class="page-title" style="margin-bottom: 0;">Configuration</h1>
        @if (repoPath()) {
          <span class="chip-mono" style="font-size: 11px;">{{ repoPath() }}</span>
        }
      </div>

      <div style="animation: fadeIn 200ms ease 40ms both;">
        <!-- Tab bar -->
        <div class="tab-bar" style="margin-bottom: var(--space-5);">
          @for (tab of tabs; track tab.id) {
            <button
              class="tab-item{{ activeTab() === tab.id ? ' tab-item--active' : '' }}"
              (click)="setActiveTab(tab.id)"
            >
              {{ tab.label }}
            </button>
          }
        </div>

        <!-- Effective read view -->
        @if (activeTab() === 'effective') {
          <div class="card">
            <div style="margin-bottom: 12px; font-size: 11px; color: var(--text-muted); font-family: var(--font-mono);">
              Merged view: project overrides global defaults
            </div>

            @if (configService.globalStatus() === 'loading') {
              <div style="padding: var(--space-6); text-align: center; color: var(--text-muted); font-size: 13px; font-family: var(--font-mono);">
                Loading...
              </div>
            } @else if (displayConfig()) {
              <app-config-table [config]="displayConfig()!" />
            } @else {
              <div style="padding: var(--space-6); text-align: center; color: var(--text-muted); font-size: 13px; font-family: var(--font-mono);">
                @if (!repoPath()) {
                  Select a repository to see effective config.
                } @else {
                  No configuration loaded.
                }
              </div>
            }
          </div>
        }

        <!-- Global edit view -->
        @if (activeTab() === 'global') {
          <div class="card">
            <div style="margin-bottom: 16px; font-size: 11px; color: var(--text-muted); font-family: var(--font-mono);">
              Global config stored at <span style="color: var(--text-secondary);">~/.config/ralph-workflow.toml</span>
            </div>
            <app-toml-editor label="Global" scope="global" [repoPath]="null" />
            <app-ai-integration-section />
          </div>
        }

        <!-- Project edit view -->
        @if (activeTab() === 'project') {
          <div class="card">
            <div style="margin-bottom: 16px; font-size: 11px; color: var(--text-muted); font-family: var(--font-mono);">
              Project-level config stored at <span style="color: var(--text-secondary);">{{ projectConfigPath() }}</span>
            </div>
            @if (!repoPath()) {
              <div style="padding: 10px 12px; background: rgba(232,168,56,0.08); border: 1px solid rgba(232,168,56,0.2); border-radius: var(--radius-md); color: var(--accent); font-size: 12px; font-family: var(--font-mono); margin-bottom: 12px;">
                Select a repository context to edit project config.
              </div>
            }
            <app-toml-editor label="Project" scope="project" [repoPath]="repoPath()" />
          </div>
        }
      </div>
    </div>
  `,
})
export class ConfigurationComponent {
  readonly configService = inject(ConfigService);
  readonly worktreesService = inject(WorktreesService);

  readonly tabs: { id: TabId; label: string }[] = [
    { id: 'effective', label: 'Effective' },
    { id: 'global', label: 'Global' },
    { id: 'project', label: 'Project' },
  ];

  readonly activeTab = signal<TabId>('effective');

  readonly repoPath = computed(() => {
    const activePath = this.worktreesService.activeWorktreePath();
    if (activePath) return activePath;
    const mainWorktree = this.worktreesService.worktrees().find(wt => wt.is_main);
    return mainWorktree?.path ?? null;
  });

  readonly displayConfig = computed(() => {
    if (this.activeTab() !== 'effective') return null;
    return this.configService.effectiveConfig() ?? this.configService.globalConfig();
  });

  readonly projectConfigPath = computed(() => {
    const repo = this.repoPath();
    return repo ? `${repo}/.ralph/config.toml` : '<repo>/.ralph/config.toml';
  });

  constructor() {
    // Fetch global config on mount
    effect(() => {
      void this.configService.fetchGlobalConfig();
    });

    // Fetch effective config when repo changes
    effect(() => {
      const repo = this.repoPath();
      if (repo) {
        void this.configService.fetchEffectiveConfig(repo);
      }
    });
  }

  setActiveTab(tab: TabId): void {
    this.activeTab.set(tab);
  }
}

@Component({
  selector: 'app-config-field',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [CommonModule],
  template: `
    <div style="display: flex; align-items: flex-start; justify-content: space-between; padding: 10px 0; border-bottom: 1px solid var(--border-subtle);">
      <div style="flex: 1;">
        <div style="font-family: var(--font-mono); font-size: 13px; color: var(--text-primary); margin-bottom: 2px;">
          {{ label() }}
        </div>
        <div style="font-size: 11px; color: var(--text-muted);">
          {{ description() }}
        </div>
      </div>
      <div [style]="valueStyle()">
        {{ displayValue() }}
      </div>
    </div>
  `,
})
export class ConfigFieldComponent {
  readonly label = input<string>('');
  readonly description = input<string>('');
  readonly value = input<string | number | boolean>('');

  displayValue = computed(() => {
    const v = this.value();
    return typeof v === 'boolean' ? (v ? 'true' : 'false') : String(v);
  });

  valueStyle = computed(() => {
    const v = this.value();
    const color = typeof v === 'boolean'
      ? v ? 'var(--status-completed)' : 'var(--text-muted)'
      : 'var(--accent)';
    return `
      font-family: var(--font-mono);
      font-size: 13px;
      color: ${color};
      margin-left: 24px;
      flex-shrink: 0;
    `.replace(/\n/g, ' ');
  });
}

@Component({
  selector: 'app-config-table',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [CommonModule, forwardRef(() => ConfigFieldComponent)],
  template: `
    <div>
      <app-config-field label="verbosity" description="Log verbosity level (0=quiet, 1=normal, 2=verbose)" [value]="config().verbosity" />
      <app-config-field label="developer_iters" description="Number of developer agent iterations per cycle" [value]="config().developer_iters" />
      <app-config-field label="reviewer_reviews" description="Number of reviewer passes per cycle" [value]="config().reviewer_reviews" />
      <app-config-field label="max_dev_continuations" description="Maximum continuation budget for developer agent" [value]="config().max_dev_continuations" />
      <app-config-field label="review_depth" description="Depth of reviewer analysis (shallow | standard | deep)" [value]="config().review_depth" />
      <app-config-field label="checkpoint_enabled" description="Persist pipeline state for --resume support" [value]="config().checkpoint_enabled" />
      <app-config-field label="isolation_mode" description="Run agents in isolated environment" [value]="config().isolation_mode" />
      <app-config-field label="interactive" description="Pause for user confirmation between phases" [value]="config().interactive" />
    </div>
  `,
})
export class ConfigTableComponent {
  readonly config = input.required<ConfigView>();
}

@Component({
  selector: 'app-toml-editor',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [CommonModule],
  template: `
    <div>
      @if (loading()) {
        <div style="padding: 8px 0; font-size: 11px; color: var(--text-muted); font-family: var(--font-mono);">
          Loading...
        </div>
      }
      <textarea
        class="form-input input-mono"
        [value]="toml()"
        (input)="onTomlInput($event)"
        [style]="textareaStyle()"
        spellcheck="false"
      ></textarea>
      @if (validationError()) {
        <div
          data-testid="toml-validation-error"
          style="margin-top: 6px; padding: 6px 10px; background: rgba(248,81,73,0.08); border: 1px solid rgba(248,81,73,0.25); border-radius: var(--radius-md); font-size: 11px; color: var(--status-failed); font-family: var(--font-mono);"
        >
          {{ validationError() }}
        </div>
      }
      <div style="display: flex; align-items: center; gap: 12px; margin-top: 10px;">
        <button
          class="btn btn-primary"
          (click)="handleSave()"
          [disabled]="isSaveDisabled()"
        >
          {{ saving() ? 'Saving...' : 'Save' }}
        </button>
        <button
          class="btn btn-ghost"
          data-testid="revert-config-button"
          (click)="handleRevert()"
          [disabled]="toml() === savedToml()"
          title="Discard unsaved changes and reload from saved state"
        >
          Revert
        </button>
        <span
          data-testid="scope-badge"
          class="chip-mono"
          style="font-size: 10px; color: var(--text-muted); text-transform: uppercase; letter-spacing: 0.08em;"
        >
          {{ scopeLabel() }}
        </span>
        @if (saveMsg()) {
          <span style="font-size: 12px; color: var(--status-completed); font-family: var(--font-mono);">
            {{ saveMsg() }}
          </span>
        }
        @if (saveError()) {
          <span style="font-size: 12px; color: var(--status-failed); font-family: var(--font-mono);">
            {{ saveError() }}
          </span>
        }
      </div>
    </div>
  `,
})
export class TomlEditorComponent {
  private readonly tauri = inject(TauriService);
  private readonly configService = inject(ConfigService);

  readonly label = input.required<string>();
  readonly repoPath = input<string | null>(null);
  readonly scope = input.required<'global' | 'project'>();

  readonly toml = signal(DEFAULT_TOML_TEMPLATE(''));
  readonly savedToml = signal(DEFAULT_TOML_TEMPLATE(''));
  readonly loading = signal(true);
  readonly saving = signal(false);
  readonly saveMsg = signal<string | null>(null);
  readonly saveError = signal<string | null>(null);
  readonly validationError = signal<string | null>(null);

  private debounceTimer: ReturnType<typeof setTimeout> | null = null;

  readonly scopeLabel = computed(() => this.scope() === 'global' ? 'global' : 'project');

  readonly isSaveDisabled = computed(() =>
    this.saving() ||
    (this.scope() === 'project' && !this.repoPath()) ||
    this.validationError() !== null
  );

  constructor() {
    // Load TOML on mount/param change
    effect(() => {
      void this.loadToml();
    });

    // Auto-clear save message after 3 seconds
    effect(() => {
      const msg = this.saveMsg();
      if (msg) {
        const timer = setTimeout(() => this.saveMsg.set(null), 3000);
        return () => clearTimeout(timer);
      }
      return;
    });
  }

  private async loadToml(): Promise<void> {
    this.loading.set(true);
    try {
      let content: string;
      if (this.scope() === 'global') {
        content = await this.tauri.getRawGlobalConfigToml();
      } else if (this.repoPath()) {
        content = await this.tauri.getRawProjectConfigToml(this.repoPath()!);
      } else {
        content = '';
      }
      const resolved = content.length > 0 ? content : DEFAULT_TOML_TEMPLATE(this.label());
      this.toml.set(resolved);
      this.savedToml.set(resolved);
    } catch {
      const fallback = DEFAULT_TOML_TEMPLATE(this.label());
      this.toml.set(fallback);
      this.savedToml.set(fallback);
    } finally {
      this.loading.set(false);
    }
  }

  onTomlInput(event: Event): void {
    const value = (event.target as HTMLTextAreaElement).value;
    this.toml.set(value);
    this.configService.setDirty(true);
    this.validateDebounced(value);
  }

  private validateDebounced(toml: string): void {
    if (this.debounceTimer !== null) {
      clearTimeout(this.debounceTimer);
    }
    this.debounceTimer = setTimeout(() => {
      void this.tauri.validateConfigToml(toml).then(error => {
        this.validationError.set(error ?? null);
      });
    }, VALIDATION_DEBOUNCE_MS);
  }

  async handleSave(): Promise<void> {
    if (this.scope() === 'project' && !this.repoPath()) return;
    if (this.validationError() !== null) return;

    this.saving.set(true);
    this.saveMsg.set(null);
    this.saveError.set(null);

    try {
      if (this.scope() === 'global') {
        await this.tauri.saveGlobalConfig(this.toml());
        await this.configService.fetchGlobalConfig();
      } else if (this.repoPath()) {
        await this.tauri.saveProjectConfig(this.repoPath()!, this.toml());
        await this.configService.fetchEffectiveConfig(this.repoPath()!);
      }
      this.savedToml.set(this.toml());
      this.saveMsg.set('Saved successfully.');
      this.configService.setDirty(false);
    } catch (e) {
      this.saveError.set(e instanceof Error ? e.message : String(e));
    } finally {
      this.saving.set(false);
    }
  }

  handleRevert(): void {
    this.toml.set(this.savedToml());
    this.validationError.set(null);
    this.configService.setDirty(false);
  }

  textareaStyle(): string {
    const hasError = this.validationError() !== null;
    return `
      min-height: 220px;
      padding: 12px 14px;
      resize: vertical;
      line-height: 1.7;
      font-size: 12px;
      border-color: ${hasError ? 'var(--status-failed)' : undefined};
      background: var(--bg-base, #0d0d0d);
      color: var(--text-primary);
    `.replace(/\n/g, ' ');
  }
}

@Component({
  selector: 'app-ai-integration-section',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [CommonModule],
  template: `
    <div style="margin-top: var(--space-6); padding-top: var(--space-6); border-top: 1px solid var(--border-subtle);">
      <!-- Section heading -->
      <div style="font-family: var(--font-display); font-size: 13px; font-weight: 600; color: var(--text-secondary); text-transform: uppercase; letter-spacing: 0.08em; margin-bottom: var(--space-3);">
        AI Integration
      </div>

      <div style="font-size: 11px; color: var(--text-muted); font-family: var(--font-mono); margin-bottom: var(--space-4);">
        Anthropic API key used for AI-assisted PROMPT.md review. Stored at
        <span style="color: var(--text-secondary);">~/.config/ralph-gui.toml</span>
        with restricted permissions (0600).
      </div>

      <!-- Key input with show/hide toggle -->
      <div style="display: flex; align-items: center; gap: var(--space-2); margin-bottom: var(--space-3);">
        <input
          [type]="showKey() ? 'text' : 'password'"
          class="form-input input-mono"
          [value]="localKey()"
          (input)="onKeyInput($event)"
          placeholder="Enter Anthropic API key (sk-ant-...)"
          style="flex: 1;"
        />
        <button class="btn btn-ghost" (click)="toggleShowKey()" style="flex-shrink: 0; min-width: 52px;">
          {{ showKey() ? 'Hide' : 'Show' }}
        </button>
      </div>

      <!-- Save button + feedback -->
      <div style="display: flex; align-items: center; gap: var(--space-3);">
        <button
          class="btn btn-primary"
          (click)="handleSave()"
          [disabled]="configService.aiApiKeySaveStatus() === 'saving'"
        >
          {{ configService.aiApiKeySaveStatus() === 'saving' ? 'Saving...' : 'Save API Key' }}
        </button>
        @if (configService.aiApiKeySaveStatus() === 'saved') {
          <span style="font-size: 12px; color: var(--status-completed); font-family: var(--font-mono);">
            Saved
          </span>
        }
        @if (configService.aiApiKeySaveStatus() === 'failed' && configService.aiApiKeyError()) {
          <span style="font-size: 12px; color: var(--status-failed); font-family: var(--font-mono);">
            {{ configService.aiApiKeyError() }}
          </span>
        }
      </div>
    </div>
  `,
})
export class AiIntegrationSectionComponent {
  readonly configService = inject(ConfigService);

  readonly localKey = signal('');
  readonly showKey = signal(false);

  constructor() {
    // Load API key on mount
    effect(() => {
      void this.configService.fetchAiApiKey();
    });

    // Sync local input when store key changes
    effect(() => {
      this.localKey.set(this.configService.aiApiKey());
    });

    // Auto-reset save status after 3 seconds
    effect(() => {
      if (this.configService.aiApiKeySaveStatus() === 'saved') {
        const timer = setTimeout(() => {
          this.configService.resetAiApiKeySaveStatus();
        }, 3000);
        return () => clearTimeout(timer);
      }
      return;
    });
  }

  onKeyInput(event: Event): void {
    this.localKey.set((event.target as HTMLInputElement).value);
  }

  toggleShowKey(): void {
    this.showKey.update(v => !v);
  }

  async handleSave(): Promise<void> {
    await this.configService.saveAiApiKey(this.localKey());
  }
}

<div class="page-content" #pageContainer>
  <div class="flex items-center justify-between mb-6 animate-fade-in">
    <h1 class="page-title mb-0">Configuration</h1>
    @if (repoPath) {
      <span class="chip-mono text-[11px]">{{ repoPath }}</span>
    }
  </div>

  <div class="flex items-center gap-3 mb-4 animate-fade-in">
    <div class="flex-1 relative">
      <input
        #searchInput
        type="text"
        [value]="searchQuery"
        (input)="setSearchQuery($any($event.target).value)"
        placeholder="Search settings..."
        class="w-full px-3 py-2 text-sm bg-zinc-900 border border-zinc-700 rounded-md text-text-primary placeholder-zinc-500 focus:outline-none focus:border-accent focus:ring-1 focus:ring-accent"
      />
      @if (searchQuery) {
        <button
          type="button"
          (click)="clearSearch()"
          class="absolute right-2 top-1/2 -translate-y-1/2 text-zinc-500 hover:text-zinc-300"
          title="Clear search"
        >
          <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" viewBox="0 0 20 20" fill="currentColor">
            <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.707 7.293a1 1 0 00-1.414 1.414L8.586 10l-1.293 1.293a1 1 0 101.414 1.414L10 11.414l1.293 1.293a1 1 0 001.414-1.414L11.414 10l1.293-1.293a1 1 0 00-1.414-1.414L10 8.586 8.707 7.293z" clip-rule="evenodd" />
          </svg>
        </button>
      }
    </div>
    <span class="text-[11px] text-zinc-500 font-mono">Ctrl+F</span>
  </div>

  <div class="animate-fade-in-delayed">
    <div class="tab-bar mb-5">
      @for (tab of tabs; track tab.id) {
        <button
          class="tab-item{{ activeTab === tab.id ? ' tab-item--active' : '' }}"
          (click)="setActiveTab(tab.id)"
        >
          {{ tab.label }}
        </button>
      }
    </div>

    @if (activeTab === 'effective') {
      <div class="card">
        <div class="mb-3 text-[11px] text-text-muted font-mono">
          Merged view: project overrides global defaults
        </div>

        @if (globalStatus === 'loading') {
          <div class="p-6 text-center text-text-muted text-[13px] font-mono">
            Loading...
          </div>
        } @else if (displayConfig) {
          <app-config-table [config]="displayConfig" [sources]="effectiveWithSources?.sources ?? null" />
        } @else {
          <div class="p-6 text-center text-text-muted text-[13px] font-mono">
            @if (!repoPath) {
              Select a repository to see effective config.
            } @else {
              No configuration loaded.
            }
          </div>
        }
      </div>
    }

    @if (activeTab === 'global') {
      <div class="card">
        <div class="mb-4 flex justify-between items-center">
          <div class="text-[11px] text-text-muted font-mono">
            Global config stored at <span class="text-text-secondary">~/.config/ralph-workflow.toml</span>
          </div>
          <button
            mat-stroked-button
            (click)="toggleViewMode()"
            class="text-[11px] min-w-0"
          >
            {{ viewMode === 'form' ? 'Raw TOML' : 'Form View' }}
          </button>
        </div>
        @if (viewMode === 'form' && globalConfig) {
          <app-config-form
            [config]="formPendingConfig ?? globalConfig"
            [searchQuery]="searchQuery"
            [defaults]="defaultConfig()"
            [sources]="effectiveWithSources?.sources ?? null"
            (configChange)="onFormConfigChange($event)"
          />
          <div class="mt-5 pt-5 border-t border-border-subtle">
            <div class="text-[13px] font-semibold mb-3 text-text-secondary">Agent Chains and Drains</div>
            <div class="text-xs text-text-muted mb-4">
              Configure named agent chains and bind them to pipeline drain phases.
            </div>
            <app-agent-chains-editor
              [toml]="rawGlobalToml"
              (tomlChange)="onChainsTomlChange($event)"
            />
          </div>
          @if (formHasPendingChanges) {
            <div class="form-save-bar">
              @if (formSaveMsg) {
                <span class="form-save-msg">{{ formSaveMsg }}</span>
              }
              @if (formSaveError) {
                <span class="form-save-error">{{ formSaveError }}</span>
              }
              <button
                type="button"
                class="btn btn-ghost"
                (click)="revertFormConfig()"
                [disabled]="formSaving"
              >Revert</button>
              <button
                type="button"
                class="btn btn-primary"
                (click)="saveFormConfig()"
                [disabled]="formSaving"
              >{{ formSaving ? 'Saving…' : 'Save' }}</button>
            </div>
          }
        } @else {
          <app-toml-editor label="Global" scope="global" [repoPath]="null" />
        }
        <app-ai-integration-section />
        <div class="mt-5 pt-5 border-t border-border-subtle">
          <div class="text-[13px] font-semibold mb-3 text-text-secondary">Agent Tools</div>
          <div class="text-xs text-text-muted mb-4">
            CLI tools Ralph delegates to for AI operations. Each tool handles its own authentication.
          </div>
          <app-agent-tools-inline />
        </div>
      </div>
    }

    @if (activeTab === 'project') {
      <div class="card">
        <div class="mb-4 flex justify-between items-center">
          <div class="text-[11px] text-text-muted font-mono">
            Project-level config stored at <span class="text-text-secondary">{{ projectConfigPath }}</span>
          </div>
          <button
            mat-stroked-button
            (click)="toggleProjectViewMode()"
            class="text-[11px] min-w-0"
          >
            {{ projectViewMode === 'form' ? 'Raw TOML' : 'Form View' }}
          </button>
        </div>
        @if (!repoPath) {
          <div class="px-3 py-2.5 bg-status-warning/8 border border-status-warning/20 rounded-md text-accent text-xs font-mono mb-3">
            Select a repository context to edit project config.
          </div>
        }
        @if (projectViewMode === 'form' && projectConfig) {
          <app-config-form
            [config]="formPendingProjectConfig ?? projectConfig"
            [searchQuery]="searchQuery"
            [defaults]="defaultConfig()"
            [sources]="effectiveWithSources?.sources ?? null"
            (configChange)="onProjectFormConfigChange($event)"
          />
          @if (hasProjectPendingChanges) {
            <div class="form-save-bar">
              <button
                type="button"
                class="btn btn-ghost"
                (click)="revertProjectFormConfig()"
              >Revert</button>
              <button
                type="button"
                class="btn btn-primary"
                (click)="saveProjectFormConfig()"
              >Save</button>
            </div>
          }
        } @else {
          <app-toml-editor label="Project" scope="project" [repoPath]="repoPath" />
        }
      </div>
    }
  </div>
</div>
