// ralph-gui/ui/src/components/sessions/PromptTemplatePicker.tsx
import { PROMPT_TEMPLATES } from "./promptTemplates";

interface PromptTemplatePickerProps {
  onSelect: (content: string) => void;
}

export function PromptTemplatePicker({ onSelect }: PromptTemplatePickerProps) {
  return (
    <div>
      <div
        className="section-label"
        style={{ marginBottom: "var(--space-4)" }}
      >
        Choose a starting template
      </div>
      <div
        style={{
          display: "grid",
          gridTemplateColumns: "repeat(auto-fill, minmax(200px, 1fr))",
          gap: 10,
        }}
      >
        {PROMPT_TEMPLATES.map((tpl) => (
          <button
            key={tpl.id}
            data-testid={`template-${tpl.id}`}
            onClick={() => onSelect(tpl.content)}
            style={{
              display: "flex",
              flexDirection: "column",
              alignItems: "flex-start",
              gap: 6,
              padding: "14px 16px",
              background: "var(--bg-surface)",
              border: "1px solid var(--border-subtle)",
              borderRadius: "var(--radius-md)",
              cursor: "pointer",
              textAlign: "left",
              transition: "border-color var(--transition-fast)",
            }}
            onMouseEnter={(e) => {
              (e.currentTarget as HTMLButtonElement).style.borderColor =
                "var(--accent)";
            }}
            onMouseLeave={(e) => {
              (e.currentTarget as HTMLButtonElement).style.borderColor =
                "var(--border-subtle)";
            }}
          >
            <span
              style={{
                fontFamily: "var(--font-display)",
                fontSize: 13,
                fontWeight: 600,
                color: "var(--text-primary)",
                letterSpacing: "-0.01em",
              }}
            >
              {tpl.label}
            </span>
            <span
              style={{
                fontSize: 11,
                color: "var(--text-muted)",
                lineHeight: 1.5,
              }}
            >
              {tpl.description}
            </span>
          </button>
        ))}
      </div>
    </div>
  );
}

// ralph-gui/ui/src/app/components/prompt-template-picker/prompt-template-picker.component.ts
import { Component, Output, EventEmitter, ChangeDetectionStrategy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { PROMPT_TEMPLATES } from '../../pages/sessions/prompt-templates';

@Component({
  selector: 'app-prompt-template-picker',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [CommonModule],
  template: `
    <div>
      <div class="section-label" style="margin-bottom: var(--space-4);">
        Choose a starting template
      </div>
      <div style="display: grid; grid-template-columns: repeat(auto-fill, minmax(200px, 1fr)); gap: 10px;">
        @for (tpl of templates; track tpl.id) {
          <button
            [attr.data-testid]="'template-' + tpl.id"
            (click)="selectTemplate.emit(tpl.content)"
            (mouseenter)="onHover($event)"
            (mouseleave)="onLeave($event)"
            style="display: flex; flex-direction: column; align-items: flex-start; gap: 6px; padding: 14px 16px; background: var(--bg-surface); border: 1px solid var(--border-subtle); border-radius: var(--radius-md); cursor: pointer; text-align: left; transition: border-color var(--transition-fast);"
          >
            <span style="font-family: var(--font-display); font-size: 13px; font-weight: 600; color: var(--text-primary); letter-spacing: -0.01em;">
              {{ tpl.label }}
            </span>
            <span style="font-size: 11px; color: var(--text-muted); line-height: 1.5;">
              {{ tpl.description }}
            </span>
          </button>
        }
      </div>
    </div>
  `,
})
export class PromptTemplatePickerComponent {
  @Output() selectTemplate = new EventEmitter<string>();

  readonly templates = PROMPT_TEMPLATES;

  onHover(event: MouseEvent): void {
    (event.currentTarget as HTMLButtonElement).style.borderColor = 'var(--accent)';
  }

  onLeave(event: MouseEvent): void {
    (event.currentTarget as HTMLButtonElement).style.borderColor = 'var(--border-subtle)';
  }
}

<div class="template-picker">

  <!-- Recently Used section (shown only when there are recently used templates) -->
  @if (hasRecent) {
    <div class="template-section" data-testid="recently-used-section">
      <div class="section-label" style="margin-bottom: var(--space-2); font-size: 11px; color: var(--text-muted); text-transform: uppercase; letter-spacing: 0.05em;">
        Recently Used
      </div>
      <div style="display: flex; flex-direction: column; gap: 6px; margin-bottom: var(--space-4);">
        @for (tpl of recentTemplates_; track tpl.id) {
          <button
            [attr.data-testid]="'recent-template-' + tpl.id"
            (click)="onSelectTemplate(tpl)"
            (mouseenter)="onHover($event)"
            (mouseleave)="onLeave($event)"
            style="display: flex; align-items: center; gap: 10px; padding: 8px 12px; background: var(--accent-subtle); border: 1px solid rgba(245,158,11,0.2); border-radius: var(--radius-md); cursor: pointer; text-align: left; transition: border-color var(--transition-fast);"
          >
            <span style="font-size: 10px; color: var(--accent);">↩</span>
            <span style="font-family: var(--font-display); font-size: 12px; font-weight: 600; color: var(--text-primary);">
              {{ tpl.label }}
            </span>
            <span style="font-size: 11px; color: var(--text-muted); margin-left: auto;">{{ tpl.description }}</span>
          </button>
        }
      </div>
    </div>
  }

  <!-- All Templates section -->
  <div class="template-section">
    <div class="section-label" style="margin-bottom: var(--space-4);">
      Choose a starting template
    </div>
    <div style="display: grid; grid-template-columns: repeat(auto-fill, minmax(200px, 1fr)); gap: 10px;">
      @for (tpl of templates; track tpl.id) {
        <button
          [attr.data-testid]="'template-' + tpl.id"
          (click)="onSelectTemplate(tpl)"
          (mouseenter)="onHover($event)"
          (mouseleave)="onLeave($event)"
          style="display: flex; flex-direction: column; align-items: flex-start; gap: 6px; padding: 14px 16px; background: var(--bg-surface); border: 1px solid var(--border-subtle); border-radius: var(--radius-md); cursor: pointer; text-align: left; transition: border-color var(--transition-fast);"
        >
          <span style="font-family: var(--font-display); font-size: 13px; font-weight: 600; color: var(--text-primary); letter-spacing: -0.01em;">
            {{ tpl.label }}
          </span>
          <span style="font-size: 11px; color: var(--text-muted); line-height: 1.5;">
            {{ tpl.description }}
          </span>
        </button>
      }
    </div>
  </div>

  <!-- Save as Template section (shown when currentPrompt has content) -->
  @if (canSaveAsTemplate) {
    <div class="template-section" style="margin-top: var(--space-4); padding-top: var(--space-4); border-top: 1px solid var(--border-subtle);" data-testid="save-as-template-section">
      <button
        class="btn btn-ghost"
        data-testid="save-as-template-btn"
        (click)="onSaveAsTemplate()"
        style="display: flex; align-items: center; gap: 8px; font-size: 12px; padding: 6px 12px; border: 1px dashed var(--border-default); border-radius: var(--radius-md); color: var(--text-secondary);"
      >
        <span>+</span>
        <span>Save current prompt as template</span>
      </button>
    </div>
  }

</div>
