// ralph-gui/ui/src/app/components/run-log/run-log.component.ts
import { Component, input, computed, ChangeDetectionStrategy } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-run-log',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [CommonModule],
  templateUrl: './run-log.component.html',
})
export class RunLogComponent {
  readonly lines = input<string[]>([]);
  readonly isLoading = input(false);
  readonly ariaLabel = input('Run log output');

  readonly logContent = computed(() => this.lines().join('\n'));
}

@if (isLoading()) {
  <div
    data-testid="run-log-loading"
    aria-busy="true"
    style="padding: 8px 0; font-size: 11px; color: var(--text-muted); font-family: var(--font-mono);"
  >
    Loading logs…
  </div>
} @else if (lines().length === 0) {
  <div
    data-testid="run-log-empty"
    role="status"
    style="padding: 8px 0; font-size: 11px; color: var(--text-muted); font-family: var(--font-mono);"
  >
    No log output yet.
  </div>
} @else {
  <pre
    data-testid="run-log-content"
    role="log"
    [attr.aria-label]="ariaLabel()"
    aria-live="polite"
    style="overflow-y: auto; max-height: 320px; font-family: var(--font-mono); font-size: 11px; line-height: 1.5; color: var(--text-secondary); background: var(--bg-base); border: 1px solid var(--border-subtle); border-radius: var(--radius-md); padding: 10px 12px; margin: 0; white-space: pre-wrap; word-break: break-all;"
  >{{ logContent() }}</pre>
}

// ralph-gui/ui/src/components/RunLog.tsx
interface RunLogProps {
  lines: string[];
  isLoading?: boolean;
  "aria-label"?: string;
}

export function RunLog({
  lines,
  isLoading = false,
  "aria-label": ariaLabel,
}: RunLogProps) {
  if (isLoading) {
    return (
      <div
        data-testid="run-log-loading"
        aria-busy="true"
        style={{
          padding: "8px 0",
          fontSize: 11,
          color: "var(--text-muted)",
          fontFamily: "var(--font-mono)",
        }}
      >
        Loading logs…
      </div>
    );
  }

  if (lines.length === 0) {
    return (
      <div
        data-testid="run-log-empty"
        role="status"
        style={{
          padding: "8px 0",
          fontSize: 11,
          color: "var(--text-muted)",
          fontFamily: "var(--font-mono)",
        }}
      >
        No log output yet.
      </div>
    );
  }

  return (
    <pre
      data-testid="run-log-content"
      role="log"
      aria-label={ariaLabel ?? "Run log output"}
      aria-live="polite"
      style={{
        overflowY: "auto",
        maxHeight: 320,
        fontFamily: "var(--font-mono)",
        fontSize: 11,
        lineHeight: 1.5,
        color: "var(--text-secondary)",
        background: "var(--bg-base)",
        border: "1px solid var(--border-subtle)",
        borderRadius: "var(--radius-md)",
        padding: "10px 12px",
        margin: 0,
        whiteSpace: "pre-wrap",
        wordBreak: "break-all",
      }}
    >
      {lines.join("\n")}
    </pre>
  );
}
