// ralph-gui/ui/src/pages/RunDetail.tsx
import { useEffect, useState } from "react";
import { useParams, useNavigate } from "react-router-dom";
import { useAppSelector, useAppDispatch } from "../store";
import {
  fetchRunDetail,
  clearRunDetail,
  startPollingInterval,
  stopPollingInterval,
} from "../store/slices/runSlice";
import { resumeInterruptedSession } from "../store/slices/sessionSlice";
import { RunStatusBadge } from "../components/RunStatusBadge";
import { RunLog } from "../components/RunLog";
import { getRunLogs } from "../api/tauri";

interface DetailRowProps {
  label: string;
  value: string | null;
  mono?: boolean;
}

function DetailRow({ label, value, mono = false }: DetailRowProps) {
  return (
    <div
      style={{
        display: "flex",
        alignItems: "flex-start",
        gap: 16,
        padding: "10px 0",
        borderBottom: "1px solid var(--border-subtle)",
      }}
    >
      <div
        style={{
          width: 160,
          flexShrink: 0,
          fontSize: 11,
          color: "var(--text-muted)",
          fontFamily: "var(--font-mono)",
          paddingTop: 1,
        }}
      >
        {label}
      </div>
      <div
        style={{
          flex: 1,
          fontSize: mono ? 12 : 13,
          color: value ? "var(--text-primary)" : "var(--text-muted)",
          fontFamily: mono ? "var(--font-mono)" : "var(--font-ui)",
          wordBreak: "break-all",
        }}
      >
        {value ?? "—"}
      </div>
    </div>
  );
}

export function RunDetail() {
  const { runId } = useParams<{ runId: string }>();
  const navigate = useNavigate();
  const dispatch = useAppDispatch();

  const runDetail = useAppSelector((s) => s.runs.runDetail);
  const status = useAppSelector((s) => s.runs.status);
  const error = useAppSelector((s) => s.runs.error);
  const pollingStatus = useAppSelector((s) => s.runs.pollingStatus);

  const detailRunId = runDetail?.run_id ?? null;
  const detailStatus = runDetail?.status ?? null;
  const detailRepoPath = runDetail?.repo_path ?? null;
  const detailWorktreePath = runDetail?.worktree_path ?? null;

  useEffect(() => {
    if (runId) {
      void dispatch(fetchRunDetail(runId));
    }
    return () => {
      dispatch(clearRunDetail());
    };
  }, [dispatch, runId]);

  useEffect(() => {
    if (!detailStatus || detailStatus !== "Running" || !detailRepoPath) return;
    stopPollingInterval();
    startPollingInterval(
      (action) => {
        void dispatch(action);
      },
      detailRepoPath,
      detailWorktreePath,
    );
    return () => {
      stopPollingInterval();
    };
  }, [dispatch, detailRunId, detailStatus, detailRepoPath, detailWorktreePath]);

  useEffect(() => {
    if (pollingStatus && runId) {
      void dispatch(fetchRunDetail(runId));
    }
  }, [dispatch, pollingStatus, runId]);

  const [logLines, setLogLines] = useState<string[]>([]);
  const [logLoading, setLogLoading] = useState(false);
  const [logExpanded, setLogExpanded] = useState(false);
  const [logFetched, setLogFetched] = useState(false);

  const handleFetchLogs = async () => {
    if (!detailRepoPath) return;
    setLogLoading(true);
    try {
      const lines = await getRunLogs(detailRepoPath, detailWorktreePath ?? null);
      setLogLines(lines);
      setLogFetched(true);
    } catch {
      setLogLines([]);
    } finally {
      setLogLoading(false);
    }
  };

  const handleToggleLogs = () => {
    const nextExpanded = !logExpanded;
    setLogExpanded(nextExpanded);
    if (nextExpanded && !logFetched) {
      void handleFetchLogs();
    }
  };

  const handleResume = async () => {
    if (!runDetail) return;
    await dispatch(
      resumeInterruptedSession({
        runId: runDetail.run_id,
        repoPath: runDetail.repo_path,
      }),
    ).unwrap();
    navigate("/sessions");
  };

  const canResume =
    runDetail?.status === "Paused" || runDetail?.status === "Failed";

  if (status === "loading") {
    return (
      <div className="page-content">
        <div
          style={{
            display: "flex",
            alignItems: "center",
            gap: 12,
            marginBottom: "var(--space-6)",
            animation: "fadeIn 200ms ease",
          }}
        >
          <button className="btn btn-ghost" onClick={() => navigate(-1)}>
            ← Back
          </button>
          <h1 className="page-title" style={{ marginBottom: 0 }}>
            Run Detail
          </h1>
        </div>
        <div
          style={{
            padding: "var(--space-10)",
            textAlign: "center",
            color: "var(--text-muted)",
            fontSize: 13,
            fontFamily: "var(--font-mono)",
          }}
        >
          Loading run...
        </div>
      </div>
    );
  }

  if (error || !runDetail) {
    return (
      <div className="page-content">
        <div
          style={{
            display: "flex",
            alignItems: "center",
            gap: 12,
            marginBottom: "var(--space-6)",
            animation: "fadeIn 200ms ease",
          }}
        >
          <button className="btn btn-ghost" onClick={() => navigate(-1)}>
            ← Back
          </button>
          <h1 className="page-title" style={{ marginBottom: 0 }}>
            Run Detail
          </h1>
        </div>
        <div className="empty-state">
          <span className="empty-state-icon">⊘</span>
          <div className="empty-state-title">Run not found</div>
          <div className="empty-state-desc">
            {error ?? "This run could not be loaded."}
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="page-content">
      {/* Header */}
      <div
        style={{
          display: "flex",
          alignItems: "center",
          gap: 12,
          marginBottom: "var(--space-6)",
          animation: "fadeIn 200ms ease",
        }}
      >
        <button className="btn btn-ghost" onClick={() => navigate(-1)}>
          ← Back
        </button>
        <h1 className="page-title" style={{ marginBottom: 0, flex: 1 }}>
          Run Detail
        </h1>
        <RunStatusBadge status={runDetail.status} showLabel isDegraded={runDetail.is_degraded} />
        {canResume && (
          <button
            className="btn btn-primary"
            onClick={() => void handleResume()}
          >
            Resume
          </button>
        )}
      </div>

      <div style={{ animation: "fadeIn 200ms ease 40ms both" }}>
        {/* Run ID banner */}
        <div
          style={{
            padding: "10px 16px",
            background: "var(--accent-bg)",
            border: "1px solid rgba(232,168,56,0.15)",
            borderRadius: "var(--radius-md)",
            fontFamily: "var(--font-mono)",
            fontSize: 12,
            color: "var(--accent)",
            marginBottom: "var(--space-5)",
            letterSpacing: "0.02em",
          }}
        >
          {runDetail.run_id}
        </div>

        {/* Degraded condition banner */}
        {runDetail.is_degraded && (
          <div
            style={{
              padding: "10px 16px",
              background: "var(--status-degraded-bg)",
              border: "1px solid var(--status-degraded-border)",
              borderRadius: "var(--radius-md)",
              color: "var(--status-degraded)",
              fontSize: 12,
              fontFamily: "var(--font-mono)",
              marginBottom: "var(--space-4)",
              display: "flex",
              alignItems: "center",
              gap: 10,
            }}
            data-testid="degraded-banner"
          >
            <span style={{ fontSize: 15, flexShrink: 0 }}>⚠</span>
            <span>
              <strong style={{ fontWeight: 600 }}>Degraded conditions</strong>
              {" "}— retries exceeded or fallback agent active. Monitor closely.
            </span>
          </div>
        )}

        {/* Details card */}
        <div className="card" style={{ marginBottom: "var(--space-5)" }}>
          <div
            style={{
              fontFamily: "var(--font-display)",
              fontSize: 13,
              fontWeight: 600,
              color: "var(--text-secondary)",
              textTransform: "uppercase",
              letterSpacing: "0.08em",
              marginBottom: 6,
            }}
          >
            Run information
          </div>

          <DetailRow label="status" value={runDetail.status} />
          <DetailRow label="phase" value={runDetail.current_phase} mono />
          <DetailRow label="agent_profile" value={runDetail.agent_profile} mono />
          <DetailRow label="repo_path" value={runDetail.repo_path} mono />
          <DetailRow
            label="worktree_path"
            value={runDetail.worktree_path}
            mono
          />
          <DetailRow label="created_at" value={runDetail.created_at} mono />
          <DetailRow
            label="last_checkpoint"
            value={runDetail.last_checkpoint}
            mono
          />
          <DetailRow
            label="iteration_count"
            value={String(runDetail.iteration_count ?? 0)}
            mono
          />
          {runDetail.last_error != null && (
            <DetailRow label="last_error" value={runDetail.last_error} mono />
          )}
          <DetailRow
            label="description"
            value={runDetail.description || null}
          />
        </div>

        {/* Phase timeline */}
        <div className="card" style={{ marginBottom: "var(--space-5)" }}>
          <div
            style={{
              fontFamily: "var(--font-display)",
              fontSize: 13,
              fontWeight: 600,
              color: "var(--text-secondary)",
              textTransform: "uppercase",
              letterSpacing: "0.08em",
              marginBottom: 20,
            }}
          >
            Phase
          </div>

          <div
            className="phase-timeline"
            style={{ alignItems: "flex-start" }}
          >
            {[
              "plan",
              "develop",
              "review",
              "commit",
            ].map((phase, idx) => {
              const currentPhase = runDetail.current_phase.toLowerCase();
              const isDone = ["commit", "done", "completed"].some((p) =>
                currentPhase.includes(p),
              )
                ? true
                : currentPhase.includes(phase)
                ? false
                : idx < ["plan", "develop", "review", "commit"].indexOf(currentPhase.split("_")[0] ?? "");
              const isCurrent = currentPhase.includes(phase);

              let dotBg = "var(--bg-elevated)";
              let dotBorder = "2px solid var(--border-default)";
              let dotColor = "var(--text-muted)";
              let labelColor = "var(--text-muted)";

              if (isCurrent) {
                dotBg = "var(--accent)";
                dotBorder = "2px solid var(--accent)";
                dotColor = "#000";
                labelColor = "var(--accent)";
              } else if (isDone) {
                dotBg = "var(--status-completed)";
                dotBorder = "2px solid var(--status-completed)";
                dotColor = "#000";
                labelColor = "var(--status-completed)";
              }

              return (
                <div
                  key={phase}
                  style={{
                    display: "flex",
                    alignItems: "flex-start",
                    flex: idx < 3 ? 1 : undefined,
                  }}
                >
                  <div className="phase-node">
                    <div
                      className="phase-node__dot"
                      style={{
                        background: dotBg,
                        border: dotBorder,
                        color: dotColor,
                        boxShadow: isCurrent ? "0 0 12px var(--accent-glow)" : "none",
                      }}
                    >
                      {isDone ? "✓" : idx + 1}
                    </div>
                    <div
                      className="phase-node__label"
                      style={{ color: labelColor }}
                    >
                      {phase}
                    </div>
                  </div>
                  {idx < 3 && (
                    <div
                      className="phase-connector"
                      style={{
                        background: isDone
                          ? "var(--status-completed)"
                          : isCurrent
                          ? "linear-gradient(90deg, var(--accent) 0%, var(--border-subtle) 100%)"
                          : "var(--border-subtle)",
                        opacity: isDone ? 1 : 0.5,
                      }}
                    />
                  )}
                </div>
              );
            })}
          </div>
        </div>

        {/* Run Log section */}
        <div className="card" style={{ marginTop: "var(--space-5)" }}>
          <div
            style={{
              display: "flex",
              alignItems: "center",
              justifyContent: "space-between",
            }}
          >
            <div
              style={{
                fontFamily: "var(--font-display)",
                fontSize: 13,
                fontWeight: 600,
                color: "var(--text-secondary)",
                textTransform: "uppercase",
                letterSpacing: "0.08em",
              }}
            >
              Run Log
            </div>
            <div style={{ display: "flex", gap: 8 }}>
              {logExpanded && logFetched && (
                <button
                  className="btn btn-ghost"
                  style={{ fontSize: 11, padding: "2px 10px" }}
                  onClick={() => void handleFetchLogs()}
                >
                  Refresh
                </button>
              )}
              <button
                className="btn btn-ghost"
                style={{ fontSize: 11, padding: "2px 10px" }}
                onClick={handleToggleLogs}
                data-testid="toggle-run-log"
              >
                {logExpanded ? "Collapse" : "Expand"}
              </button>
            </div>
          </div>
          {logExpanded && (
            <div style={{ marginTop: 12 }}>
              <RunLog lines={logLines} isLoading={logLoading} />
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

// ralph-gui/ui/src/app/pages/run-detail/run-detail.component.ts
import {
  Component,
  inject,
  signal,
  effect,
  computed,
  input,
  ChangeDetectionStrategy,
  forwardRef,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { ActivatedRoute, Router, RouterModule } from '@angular/router';
import { RunsService } from '../../services/runs.service';
import { TauriService } from '../../services/tauri.service';
import { RunStatusBadgeComponent } from '../../components/run-status-badge/run-status-badge.component';
import { RunLogComponent } from '../../components/run-log/run-log.component';
import { ChangesViewerComponent } from '../../components/changes-viewer/changes-viewer.component';
import { PhaseTimelineComponent, PhaseInfo } from '../../components/phase-timeline/phase-timeline.component';

export type DetailTab = 'log' | 'changes' | 'info';

@Component({
  selector: 'app-run-detail',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [
    CommonModule,
    RouterModule,
    RunStatusBadgeComponent,
    RunLogComponent,
    ChangesViewerComponent,
    PhaseTimelineComponent,
    forwardRef(() => DetailRowComponent),
  ],
  templateUrl: './run-detail.component.html',
  styleUrl: './run-detail.component.css',
})
export class RunDetailComponent {
  private readonly route = inject(ActivatedRoute);
  private readonly router = inject(Router);
  readonly runsService = inject(RunsService);
  private readonly tauri = inject(TauriService);

  // Computed from service
  readonly runDetail = this.runsService.runDetail;
  readonly isLoading = computed(() => this.runsService.status() === 'loading');
  readonly error = this.runsService.error;

  // Tab state — default depends on run status
  readonly activeTab = signal<DetailTab>('log');

  readonly canResume = computed(() => {
    const detail = this.runDetail();
    return detail && (detail.status === 'Paused' || detail.status === 'Failed');
  });

  readonly iterationCount = computed(() => {
    return String(this.runDetail()?.iteration_count ?? 0);
  });

  /** Convert RunDetail phases to PhaseInfo[] for the PhaseTimelineComponent. */
  readonly timelinePhases = computed((): PhaseInfo[] => {
    const detail = this.runDetail();
    if (!detail) return [];

    const phases = ['Plan', 'Develop', 'Review', 'Commit'];
    const currentPhase = detail.current_phase.toLowerCase();
    const isDone = ['commit', 'done', 'completed'].some(p => currentPhase.includes(p));
    const phaseOrder = ['plan', 'develop', 'review', 'commit'];
    const currentIdx = phaseOrder.indexOf(currentPhase.split('_')[0] ?? '');

    return phases.map((name, idx) => {
      let status: PhaseInfo['status'];
      if (isDone || idx < currentIdx) {
        status = 'completed';
      } else if (idx === currentIdx && !isDone) {
        status = detail.status === 'Failed' ? 'failed' : 'active';
      } else {
        status = 'pending';
      }
      return { name, status };
    });
  });

  constructor() {
    // Fetch run detail on route param change
    effect(() => {
      const runId = this.route.snapshot.paramMap.get('runId');
      if (runId) {
        void this.runsService.fetchRunDetail(runId);
      }
    });

    // Start polling when run is running
    effect((onCleanup) => {
      const detail = this.runDetail();
      if (detail?.status === 'Running' && detail.repo_path) {
        this.runsService.startPolling(detail.repo_path, detail.worktree_path);
        onCleanup(() => this.runsService.stopPolling());
      }
    });

    // Set default tab based on run status when detail loads
    effect(() => {
      const detail = this.runDetail();
      if (!detail) return;
      switch (detail.status) {
        case 'Completed':
          this.activeTab.set('changes');
          break;
        case 'Failed':
        case 'Paused':
        case 'Running':
          this.activeTab.set('log');
          break;
        default:
          this.activeTab.set('log');
      }
    });

    // Refresh detail when polling status changes
    effect(() => {
      const pollingStatus = this.runsService.pollingStatus();
      const runId = this.route.snapshot.paramMap.get('runId');
      if (pollingStatus && runId) {
        void this.runsService.fetchRunDetail(runId);
      }
    });

    // Cleanup on destroy
    effect((onCleanup) => {
      onCleanup(() => {
        this.runsService.clearRunDetail();
        this.runsService.stopPolling();
      });
    });
  }

  goBack(): void {
    void this.router.navigate(['/sessions']);
  }

  setTab(tab: DetailTab): void {
    this.activeTab.set(tab);
  }

  async handleResume(): Promise<void> {
    const detail = this.runDetail();
    if (!detail) return;

    try {
      await this.tauri.resumeRalphSession(detail.run_id, detail.repo_path);
      void this.router.navigate(['/sessions']);
    } catch (e) {
      console.error('Failed to resume session:', e);
    }
  }

  async handleCancel(): Promise<void> {
    const detail = this.runDetail();
    if (!detail) return;

    const confirmed = window.confirm('Cancel this run? Progress up to the last checkpoint will be saved.');
    if (!confirmed) return;

    try {
      await this.tauri.cancelRun(detail.repo_path, detail.worktree_path);
      void this.router.navigate(['/sessions']);
    } catch (e) {
      console.error('Failed to cancel run:', e);
    }
  }

  async handleRetry(): Promise<void> {
    const detail = this.runDetail();
    if (!detail) return;

    const confirmed = window.confirm('Retry this run from the beginning?');
    if (!confirmed) return;

    try {
      await this.tauri.resumeRalphSession(detail.run_id, detail.repo_path);
      void this.router.navigate(['/sessions']);
    } catch (e) {
      console.error('Failed to retry session:', e);
    }
  }

  onPhaseClick(_phase: PhaseInfo): void {
    // Navigate to log tab when a completed phase is clicked (future: filter by phase)
    this.activeTab.set('log');
  }

  get isLoadingValue(): boolean { return this.isLoading(); }
  get errorValue(): string | null { return this.error(); }
  get runDetailValue() { return this.runDetail(); }
  get canResumeValue() { return this.canResume(); }
  get activeTabValue(): DetailTab { return this.activeTab(); }
  get timelinePhasesValue(): PhaseInfo[] { return this.timelinePhases(); }
  get iterationCountValue(): string { return this.iterationCount(); }
}

@Component({
  selector: 'app-detail-row',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [CommonModule],
  templateUrl: './detail-row.component.html',
})
export class DetailRowComponent {
  readonly label = input<string>('');
  readonly value = input<string | null>(null);
  readonly mono = input<boolean>(false);

  get labelValue(): string { return this.label(); }
  get valueValue(): string | null { return this.value(); }

  get valueStyle(): string {
    const isMono = this.mono();
    return `
      flex: 1;
      font-size: ${isMono ? 12 : 13}px;
      color: ${this.value() ? 'var(--text-primary)' : 'var(--text-muted)'};
      font-family: ${isMono ? 'var(--font-mono)' : 'var(--font-ui)'};
      word-break: break-all;
    `.replace(/\n/g, ' ');
  }
}

<div class="page-content">
  @if (isLoadingValue) {
    <div class="run-header">
      <button class="btn btn-ghost" (click)="goBack()">← Back</button>
      <h1 class="page-title run-header__title">Run Detail</h1>
    </div>
    <div class="run-loading">Loading run...</div>
  } @else if (errorValue || !runDetailValue) {
    <div class="run-header">
      <button class="btn btn-ghost" (click)="goBack()">← Back</button>
      <h1 class="page-title run-header__title">Run Detail</h1>
    </div>
    <div class="empty-state">
      <span class="empty-state-icon">⊘</span>
      <div class="empty-state-title">Run not found</div>
      <div class="empty-state-desc">{{ errorValue ?? 'This run could not be loaded.' }}</div>
    </div>
  } @else {
    <!-- Page header -->
    <div class="run-header">
      <button class="btn btn-ghost" (click)="goBack()">← Back</button>
      <h1 class="page-title run-header__title">Run Detail</h1>
      <app-run-status-badge
        [status]="runDetailValue!.status"
        [showLabel]="true"
        [isDegraded]="runDetailValue!.is_degraded ?? false"
      />
      @if (runDetailValue!.status === 'Running') {
        <button
          class="btn btn-ghost btn-danger"
          data-testid="cancel-btn"
          (click)="handleCancel()"
        >
          Cancel
        </button>
      }
      @if (canResumeValue) {
        <button
          class="btn btn-primary"
          data-testid="resume-btn"
          (click)="handleResume()"
        >
          Resume
        </button>
      }
    </div>

    <div class="run-detail-body">
      <!-- Run ID badge -->
      <div class="run-id-badge">{{ runDetailValue!.run_id }}</div>

      <!-- Degraded banner -->
      @if (runDetailValue!.is_degraded) {
        <div class="banner banner--warning" data-testid="degraded-banner">
          <span class="banner__icon">⚠</span>
          <span>
            <strong>Degraded conditions</strong>
            — retries exceeded or fallback agent active. Monitor closely.
          </span>
        </div>
      }

      <!-- State-specific banners -->
      @if (runDetailValue!.status === 'Completed') {
        <div class="banner banner--success" data-testid="completed-banner">
          <span class="banner__icon">✓</span>
          <div class="banner__content">
            <strong>Completed</strong>
            <div class="metric-grid">
              <div class="metric-card">
                <span class="metric-card__label">Iterations</span>
                <span class="metric-card__value">{{ runDetailValue!.iteration_count ?? 0 }}</span>
              </div>
              <div class="metric-card">
                <span class="metric-card__label">Phase</span>
                <span class="metric-card__value">{{ runDetailValue!.current_phase }}</span>
              </div>
            </div>
          </div>
        </div>
      }

      @if (runDetailValue!.status === 'Failed') {
        <div class="banner banner--error" data-testid="failed-banner">
          <span class="banner__icon">✗</span>
          <div class="banner__content">
            <strong>Failed</strong>
            @if (runDetailValue!.last_error) {
              <div class="banner__error-msg">{{ runDetailValue!.last_error }}</div>
            }
            <div class="banner__actions">
              <button class="btn btn-ghost" (click)="handleRetry()">Retry from Beginning</button>
              <a class="btn btn-ghost" routerLink="/configuration">Go to Config →</a>
            </div>
          </div>
        </div>
      }

      @if (runDetailValue!.status === 'Paused') {
        <div class="banner banner--paused" data-testid="paused-banner">
          <span class="banner__icon">⏸</span>
          <div class="banner__content">
            <strong>Paused at checkpoint</strong>
            <div class="banner__subtitle">
              Will resume from iteration {{ runDetailValue!.iteration_count ?? 0 }}
            </div>
            <div class="banner__actions">
              <button class="btn btn-primary" (click)="handleResume()">Resume</button>
            </div>
          </div>
        </div>
      }

      <!-- Phase Timeline (extracted component) -->
      <div class="card run-phase-card">
        <div class="card-section-label">Phase</div>
        <app-phase-timeline
          [phases]="timelinePhasesValue"
          (phaseClick)="onPhaseClick($event)"
        />
      </div>

      <!-- Tab bar -->
      <div class="run-tabs" role="tablist" aria-label="Run detail tabs">
        <button
          class="run-tab"
          [class.run-tab--active]="activeTabValue === 'log'"
          role="tab"
          [attr.aria-selected]="activeTabValue === 'log'"
          data-testid="tab-log"
          (click)="setTab('log')"
        >
          Log
        </button>
        <button
          class="run-tab"
          [class.run-tab--active]="activeTabValue === 'changes'"
          role="tab"
          [attr.aria-selected]="activeTabValue === 'changes'"
          data-testid="tab-changes"
          (click)="setTab('changes')"
        >
          Changes
        </button>
        <button
          class="run-tab"
          [class.run-tab--active]="activeTabValue === 'info'"
          role="tab"
          [attr.aria-selected]="activeTabValue === 'info'"
          data-testid="tab-info"
          (click)="setTab('info')"
        >
          Info
        </button>
      </div>

      <!-- Tab content -->
      @if (activeTabValue === 'log') {
        <div class="card run-tab-content" data-testid="tab-content-log">
          <app-run-log
            [runId]="runDetailValue!.run_id"
            [repoPath]="runDetailValue!.repo_path"
            [worktreePath]="runDetailValue!.worktree_path"
          />
        </div>
      }

      @if (activeTabValue === 'changes') {
        <div class="card run-tab-content" data-testid="tab-content-changes">
          <app-changes-viewer
            [runId]="runDetailValue!.run_id"
            [repoPath]="runDetailValue!.repo_path"
            [worktreePath]="runDetailValue!.worktree_path"
          />
        </div>
      }

      @if (activeTabValue === 'info') {
        <div class="card run-tab-content" data-testid="tab-content-info">
          <div class="card-section-label">Run Information</div>
          <app-detail-row label="status" [value]="runDetailValue!.status" [mono]="true" />
          <app-detail-row label="phase" [value]="runDetailValue!.current_phase" [mono]="true" />
          <app-detail-row label="agent_profile" [value]="runDetailValue!.agent_profile" [mono]="true" />
          <app-detail-row label="repo_path" [value]="runDetailValue!.repo_path" [mono]="true" />
          <app-detail-row label="worktree_path" [value]="runDetailValue!.worktree_path" [mono]="true" />
          <app-detail-row label="created_at" [value]="runDetailValue!.created_at" [mono]="true" />
          <app-detail-row label="last_checkpoint" [value]="runDetailValue!.last_checkpoint" [mono]="true" />
          <app-detail-row label="iteration_count" [value]="iterationCountValue" [mono]="true" />
           @if (runDetailValue!.last_error) {
             <app-detail-row label="last_error" [value]="runDetailValue!.last_error || null" [mono]="true" />
           }
          <app-detail-row label="description" [value]="runDetailValue!.description || null" [mono]="false" />
        </div>
      }
    </div>
  }
</div>
